import { NavItem } from './nav-items';
import {
  WORDS_ROUTE_PATH,
  lemmasRoutePath,
  phraseSearchBaseRoutePath,
  phraseSearchRoutePath,
  rootsRoutePath,
  stemsRoutePath,
  uniqueWordsRoutePath,
  wordTypesRoutePath,
} from './route-paths';

export const WORDS_MENU_ITEMS: readonly NavItem[] = [
  {
    key: 'words-home',
    labelAr: 'الرئيسية',
    labelEn: 'Home',
    route: WORDS_ROUTE_PATH,
    icon: 'words',
    group: 'primary',
  },
  {
    key: 'words-unique',
    labelAr: 'الكلمات الفريدة',
    labelEn: 'Unique Words',
    route: uniqueWordsRoutePath('tashkeel'),
    resumePath: `${WORDS_ROUTE_PATH}/unique`,
    icon: 'tag',
    group: 'primary',
  },
  {
    key: 'words-roots',
    labelAr: 'الجذور',
    labelEn: 'Roots',
    route: rootsRoutePath(),
    icon: 'root',
    group: 'primary',
  },
  {
    key: 'words-lemmas',
    labelAr: 'الصيغ المعجمية',
    labelEn: 'Lemmas',
    route: lemmasRoutePath(),
    icon: 'lemma',
    group: 'primary',
  },
  {
    key: 'words-stems',
    labelAr: 'الأصول الصرفية',
    labelEn: 'Stems',
    route: stemsRoutePath(),
    icon: 'stem',
    group: 'primary',
  },
  {
    key: 'words-types',
    labelAr: 'أنواع الكلمات',
    labelEn: 'Word Types',
    route: wordTypesRoutePath(),
    icon: 'template',
    group: 'primary',
  },
  {
    key: 'words-phrases',
    labelAr: 'البحث في القرآن',
    labelEn: 'Quran Phrase Search',
    route: phraseSearchRoutePath(),
    resumePath: phraseSearchBaseRoutePath(),
    icon: 'search',
    group: 'primary',
  },
];
