/* eslint-disable */
/* Code generated by scripts/generate-permission-codes.mjs DO NOT EDIT. */

export const ABWAB_PERMISSION_CODES = {
  doors: {
    create: 'abwab.doors.create',
    edit: 'abwab.doors.edit',
    move: 'abwab.doors.move',
    reorder: 'abwab.doors.reorder',
    archive: 'abwab.doors.archive',
    restore: 'abwab.doors.restore',
  },
  sections: {
    create: 'abwab.sections.create',
    edit: 'abwab.sections.edit',
    reorder: 'abwab.sections.reorder',
    delete: 'abwab.sections.delete',
  },
  relations: {
    create: 'abwab.relations.create',
    delete: 'abwab.relations.delete',
  },
  templates: {
    create: 'abwab.templates.create',
    delete: 'abwab.templates.delete',
    apply: 'abwab.templates.apply',
  },
  templateNodes: {
    create: 'abwab.template_nodes.create',
    edit: 'abwab.template_nodes.edit',
    reorder: 'abwab.template_nodes.reorder',
    delete: 'abwab.template_nodes.delete',
  },
} as const;
