using System.Security.Cryptography;
using System.Text.Encodings.Web;
using System.Text.Json;
using QuranDashboard.Application.Abstractions.Quran.DataPipelines.Tafsirs;
using QuranDashboard.Infrastructure.Files.Quran.DataPipelines.Tafsirs;

namespace QuranDashboard.Tests.Quran.Tafsirs;

public sealed class TafsirSyntheticPackage : IDisposable
{
    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping,
        WriteIndented = true
    };

    private readonly List<string> tempDirs = [];
    private bool disposed;

    public void Dispose()
    {
        if (disposed)
        {
            return;
        }

        foreach (var dir in tempDirs)
        {
            try
            {
                Directory.Delete(dir, recursive: true);
            }
            catch (IOException)
            {
            }
            catch (UnauthorizedAccessException)
            {
            }
        }

        tempDirs.Clear();
        disposed = true;
    }

    public async Task<string> WriteAsync(
        IReadOnlyList<SyntheticTafsirSourceSpec>? sources = null,
        IReadOnlyList<string>? excludedSourceKeys = null,
        string manifestType = TafsirSyntheticSeed.ManifestType,
        bool isFinalImportManifest = true)
    {
        var sourceSpecs = sources ?? TafsirSyntheticSeed.DefaultSources;
        var excluded = excludedSourceKeys ?? Array.Empty<string>();

        var packageDir = Path.Combine(Path.GetTempPath(), $"quran-tafsirs-{Guid.NewGuid():N}");
        tempDirs.Add(packageDir);
        Directory.CreateDirectory(packageDir);
        Directory.CreateDirectory(Path.Combine(packageDir, "sources"));

        await File.WriteAllTextAsync(
            Path.Combine(packageDir, "README.md"),
            "Synthetic tafsir source package for tests. Source-safe; not for import into production.");
        await File.WriteAllTextAsync(
            Path.Combine(packageDir, "package-report.md"),
            "# Synthetic tafsir package report\n\nGenerated by TafsirSyntheticPackage for tests.");

        var sourceRecords = new List<object>();
        foreach (var spec in sourceSpecs)
        {
            var packageFile = $"sources/{spec.SourceKey}.json";
            var fullPath = Path.Combine(packageDir, packageFile);
            await WriteJsonAsync(fullPath, spec.Entries);

            var fileInfo = new FileInfo(fullPath);
            sourceRecords.Add(BuildSourceRecord(spec, packageFile, fileInfo.Length, ComputeSha256(fullPath)));
        }

        var manifest = BuildManifest(
            manifestType,
            isFinalImportManifest,
            sourceSpecs,
            sourceRecords,
            excluded);

        await WriteJsonAsync(Path.Combine(packageDir, "manifest.json"), manifest);
        return packageDir;
    }

    public async Task TamperManifestFieldAsync(string packageDir, string fieldPath, object value)
    {
        var manifestPath = Path.Combine(packageDir, "manifest.json");
        Dictionary<string, JsonElement> root;
        await using (var stream = File.OpenRead(manifestPath))
        {
            using var document = await JsonDocument.ParseAsync(stream);
            root = JsonSerializer.Deserialize<Dictionary<string, JsonElement>>(document.RootElement.GetRawText())!;
        }

        var rebuilt = new Dictionary<string, object?>();
        foreach (var (key, element) in root)
        {
            rebuilt[key] = key == fieldPath
                ? value
                : JsonElementToObject(element);
        }

        await WriteJsonAsync(manifestPath, rebuilt);
    }

    public async Task TamperManifestSummaryFieldAsync(string packageDir, string summaryField, object value)
    {
        var manifestPath = Path.Combine(packageDir, "manifest.json");
        Dictionary<string, JsonElement> root;
        await using (var stream = File.OpenRead(manifestPath))
        {
            using var document = await JsonDocument.ParseAsync(stream);
            root = JsonSerializer.Deserialize<Dictionary<string, JsonElement>>(document.RootElement.GetRawText())!;
        }

        var summary = JsonSerializer.Deserialize<Dictionary<string, object?>>(
            root["summary"].GetRawText())!;
        summary[summaryField] = value;

        var rebuilt = new Dictionary<string, object?>();
        foreach (var (key, element) in root)
        {
            rebuilt[key] = key == "summary" ? summary : JsonElementToObject(element);
        }

        await WriteJsonAsync(manifestPath, rebuilt);
    }

    public async Task RefreshManifestChecksumsAsync(string packageDir)
    {
        var manifestPath = Path.Combine(packageDir, "manifest.json");

        await using var stream = File.OpenRead(manifestPath);
        using var document = await JsonDocument.ParseAsync(stream);
        var root = document.RootElement.Clone();
        await stream.DisposeAsync();

        var manifest = JsonSerializer.Deserialize<Dictionary<string, JsonElement>>(root.GetRawText())!;

        var refreshedSources = new List<object>();
        foreach (var sourceElement in root.GetProperty("sources").EnumerateArray())
        {
            var record = JsonSerializer.Deserialize<Dictionary<string, JsonElement>>(sourceElement.GetRawText())!;
            var packageFile = record["packageFile"].GetString()!;
            var fullPath = Path.Combine(packageDir, packageFile);
            var fileInfo = new FileInfo(fullPath);

            var rebuilt = new Dictionary<string, object?>();
            foreach (var (key, value) in record)
            {
                rebuilt[key] = JsonElementToObject(value);
            }

            rebuilt["fileSizeBytes"] = fileInfo.Length;
            rebuilt["sha256"] = ComputeSha256(fullPath);
            refreshedSources.Add(rebuilt);
        }

        var rebuiltManifest = new Dictionary<string, object?>();
        foreach (var (key, value) in manifest)
        {
            rebuiltManifest[key] = key == "sources" ? refreshedSources : JsonElementToObject(value);
        }

        await WriteJsonAsync(manifestPath, rebuiltManifest);
    }

    public static async Task<string> ComputePackageFileSha256Async(string packageDir, string relativePath)
    {
        var fullPath = Path.Combine(packageDir, relativePath.Replace('\\', '/'));
        return Convert.ToHexString(SHA256.HashData(await File.ReadAllBytesAsync(fullPath)));
    }

    private static object BuildSourceRecord(
        SyntheticTafsirSourceSpec spec,
        string packageFile,
        long fileSize,
        string sha256) =>
        new
        {
            sourceKey = spec.SourceKey,
            languageCode = spec.LanguageCode,
            languageNameAr = spec.LanguageNameAr,
            languageNameEn = spec.LanguageNameEn,
            direction = spec.Direction,
            displayNameAr = spec.NativeName,
            shortNameAr = spec.NativeName,
            displayNameEn = spec.SourceKey,
            shortNameEn = spec.SourceKey,
            contributorKey = (string?)null,
            contributorNameAr = (string?)null,
            contributorNameEn = (string?)null,
            contributorType = "scholar",
            resourceKind = "tafsir",
            tafsirKind = spec.TafsirKind,
            contentCoverageCount = (short)spec.ContentCoverageCount,
            packageFile,
            sourceFileOriginal = packageFile,
            sha256,
            fileSizeBytes = fileSize,
            license = (string?)null,
            provenance = (string?)null
        };

    private static object BuildManifest(
        string manifestType,
        bool isFinalImportManifest,
        IReadOnlyList<SyntheticTafsirSourceSpec> sources,
        IReadOnlyList<object> sourceRecords,
        IReadOnlyList<string> excluded)
    {
        var languages = sources.Select(s => s.LanguageCode).Distinct().Count();
        var arabicSources = sources.Count(s => s.LanguageCode == "ar");
        var nonArabicSources = sources.Count - arabicSources;

        return new
        {
            manifestVersion = "1.0",
            manifestType,
            isFinalImportManifest,
            sourceCount = sources.Count,
            canonicalSource = new
            {
                corpusName = "QuranicAudio / Tafsir Collection",
                archivePath = "/synthetic/test/corpus.tar.gz",
                extractedRoot = "/synthetic/test/extracted",
                upstreamPublishedAtUtc = "2026-01-01T00:00:00Z",
                packageCreatedAtUtc = "2026-01-01T00:00:00Z"
            },
            summary = new
            {
                totalSourcesScanned = sources.Count + excluded.Count,
                copiedApprovedTafsirSources = sources.Count,
                excludedSources = excluded.Count,
                arabicApprovedCopied = arabicSources,
                nonArabicApprovedCopied = nonArabicSources,
                languageCount = languages
            },
            sources = sourceRecords,
            excludedSourceSummary = excluded.Select(key => new
            {
                sourceKey = key,
                status = "excluded",
                resourceKind = "tafsir",
                contentCoverageCount = 0,
                sourceFileOriginal = $"sources/{key}.json",
                reviewReason = "Locked excluded source for testing"
            }).ToList()
        };
    }

    private static string ComputeSha256(string fullPath) =>
        Convert.ToHexString(SHA256.HashData(File.ReadAllBytes(fullPath)));

    private static async Task WriteJsonAsync(string path, object content)
    {
        await using var stream = File.Create(path);
        await JsonSerializer.SerializeAsync(stream, content, JsonOptions);
    }

    private static object? JsonElementToObject(JsonElement element) => element.ValueKind switch
    {
        JsonValueKind.String => element.GetString(),
        JsonValueKind.Number => element.TryGetInt64(out var l) ? l : element.GetDouble(),
        JsonValueKind.True => true,
        JsonValueKind.False => false,
        JsonValueKind.Null => null,
        JsonValueKind.Array => element.EnumerateArray().Select(JsonElementToObject).ToList(),
        JsonValueKind.Object => element.EnumerateObject()
            .ToDictionary(p => p.Name, p => JsonElementToObject(p.Value)),
        _ => element.GetRawText()
    };
}
