<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\domain\QuranDashboard.Domain\QuranDashboard.Domain.csproj" />
    <ProjectReference Include="..\..\shared\QuranDashboard.Shared\QuranDashboard.Shared.csproj" />
  </ItemGroup>

</Project>
