using QuranDashboard.Application.Abstractions.Quran.DataPipelines.Words.SimpleI3rabGeneration;
using QuranDashboard.Domain.Quran.Words.Morphology.Irab;

namespace QuranDashboard.Infrastructure.Files.Quran.DataPipelines.Words.SimpleI3rabGeneration;

internal static class I3rabRuleCatalogSeedData
{
    internal static IReadOnlyList<I3rabRuleSeedRow> BuildRows() =>
    [
        new("STEM:N:GEN", "N.GEN", "اسم مجرور", I3rabStatusMapping.Approved, null, 1),
        new("PREFIX:CONJ", "CONJ.PREFIX", "حرف عطف", I3rabStatusMapping.Approved, null, 2),
        new("PREFIX:DET", "DET", "أداة تعريف", I3rabStatusMapping.Approved, null, 3),
        new("STEM:N:ACC", "N.ACC", "اسم منصوب", I3rabStatusMapping.Approved, null, 4),
        new("STEM:P", "P.STEM", "حرف جر", I3rabStatusMapping.Approved, null, 5),
        new("SUFFIX:PRON:3MP", "PRON.SUF", "ضمير متصل للغائبين", I3rabStatusMapping.Approved, null, 6),
        new("STEM:N:NOM", "N.NOM", "اسم مرفوع", I3rabStatusMapping.Approved, null, 7),
        new("PREFIX:P", "P.PREFIX", "حرف جر", I3rabStatusMapping.Approved, null, 8),
        new("SUFFIX:PRON:2MP", "PRON.SUF", "ضمير متصل للمخاطبين", I3rabStatusMapping.Approved, null, 9),
        new("STEM:V:PERF:ACT:3MS", "V.PERF.ACT", "فعل ماض", I3rabStatusMapping.Approved, null, 10),
        new("STEM:REL", "REL", "اسم موصول", I3rabStatusMapping.Approved, null, 11),
        new("PREFIX:REM", "REM", "حرف استئناف", I3rabStatusMapping.Approved, null, 12),
        new("SUFFIX:PRON:3MS", "PRON.SUF", "ضمير متصل للغائب", I3rabStatusMapping.Approved, null, 13),
        new("STEM:NEG", "NEG", "حرف نفي", I3rabStatusMapping.Approved, null, 14),
        new("STEM:V:IMPF:ACT:3MS", "V.IMPF.ACT", "فعل مضارع", I3rabStatusMapping.Approved, null, 15),
        new("SUFFIX:PRON:1P", "PRON.SUF", "ضمير متصل لجماعة المتكلمين", I3rabStatusMapping.Approved, null, 16),
        new("STEM:ACC", "ACC", "حرف نصب (من أخوات إنّ/النواصب)", I3rabStatusMapping.Approved, null, 17),
        new("STEM:V:PERF:ACT:3MP", "V.PERF.ACT", "فعل ماض", I3rabStatusMapping.Approved, null, 18),
        new("STEM:V:IMPF:ACT:3MP", "V.IMPF.ACT", "فعل مضارع", I3rabStatusMapping.Approved, null, 19),
        new("SUFFIX:PRON:2MS", "PRON.SUF", "ضمير متصل للمخاطب", I3rabStatusMapping.Approved, null, 20),
        new("STEM:V:PERF:ACT:1P", "V.PERF.ACT", "فعل ماض", I3rabStatusMapping.Approved, null, 21),
        new("SUFFIX:PRON:1S", "PRON.SUF", "ضمير متصل للمتكلم المفرد", I3rabStatusMapping.Approved, null, 22),
        new("STEM:V:IMPF:ACT:2MP", "V.IMPF.ACT", "فعل مضارع", I3rabStatusMapping.Approved, null, 23),
        new("STEM:T", "T.TIME", "ظرف زمان", I3rabStatusMapping.Approved, null, 24),
        new("STEM:PN:ALLAH:GEN", "PN.ALLAH.GEN", "لفظ الجلالة مجرور", I3rabStatusMapping.Approved, null, 25),
        new("STEM:PRON:3MS", "PRON.STEM", "ضمير للغائب", I3rabStatusMapping.Approved, null, 26),
        new("SUFFIX:PRON:3FS", "PRON.SUF", "ضمير متصل للغائبة", I3rabStatusMapping.Approved, null, 27),
        new("STEM:COND", "COND", "أداة شرط", I3rabStatusMapping.Approved, null, 28),
        new("STEM:DEM", "DEM", "اسم إشارة", I3rabStatusMapping.Approved, null, 29),
        new("PREFIX:EMPH", "EMPH.PREFIX", "لام التوكيد (المزحلقة)", I3rabStatusMapping.Approved, null, 30),
        new("STEM:PN:ALLAH:NOM", "PN.ALLAH.NOM", "لفظ الجلالة مرفوع", I3rabStatusMapping.Approved, null, 31),
        new("STEM:V:IMPV:ACT:2MS", "V.IMPV.ACT", "فعل أمر", I3rabStatusMapping.Approved, null, 32),
        new("STEM:PRON:3MP", "PRON.STEM", "ضمير للغائبين", I3rabStatusMapping.Approved, null, 33),
        new("STEM:V:IMPV:ACT:2MP", "V.IMPV.ACT", "فعل أمر", I3rabStatusMapping.Approved, null, 34),
        new("STEM:ADJ:NOM", "ADJ.NOM", "صفة مرفوعة", I3rabStatusMapping.Approved, null, 35),
        new("STEM:CONJ", "CONJ.STEM", "حرف عطف", I3rabStatusMapping.Approved, null, 36),
        new("STEM:SUB", "SUB", "حرف مصدري", I3rabStatusMapping.Approved, null, 37),
        new("STEM:LOC", "LOC", "ظرف مكان", I3rabStatusMapping.Approved, null, 38),
        new("STEM:V:IMPF:ACT:1P", "V.IMPF.ACT", "فعل مضارع", I3rabStatusMapping.Approved, null, 39),
        new("STEM:PN:ALLAH:ACC", "PN.ALLAH.ACC", "لفظ الجلالة منصوب", I3rabStatusMapping.Approved, null, 40),
        new("STEM:ADJ:ACC", "ADJ.ACC", "صفة منصوبة", I3rabStatusMapping.Approved, null, 41),
        new("STEM:V:PERF:ACT:2MP", "V.PERF.ACT", "فعل ماض", I3rabStatusMapping.Approved, null, 42),
        new("STEM:RES", "RES", "أداة حصر", I3rabStatusMapping.Approved, null, 43),
        new("STEM:PN:GEN", "PN.GEN", "اسم علم مجرور", I3rabStatusMapping.Approved, null, 44),
        new("STEM:PRON:2MP", "PRON.STEM", "ضمير للمخاطبين", I3rabStatusMapping.Approved, null, 45),
        new("STEM:ADJ:GEN", "ADJ.GEN", "صفة مجرورة", I3rabStatusMapping.Approved, null, 46),
        new("PREFIX:INTG", "INTG.PREFIX", "همزة استفهام", I3rabStatusMapping.Approved, null, 47),
        new("STEM:V:IMPF:ACT:2MS", "V.IMPF.ACT", "فعل مضارع", I3rabStatusMapping.Approved, null, 48),
        new("STEM:V:PERF:ACT:3FS", "V.PERF.ACT", "فعل ماض", I3rabStatusMapping.Approved, null, 49),
        new("STEM:V:IMPF:ACT:3FS", "V.IMPF.ACT", "فعل مضارع", I3rabStatusMapping.Approved, null, 50),
        new("STEM:INTG", "INTG.STEM", "اسم استفهام", I3rabStatusMapping.Approved, null, 51),
        new("STEM:CERT", "CERT", "حرف تحقيق (قد)", I3rabStatusMapping.Approved, null, 52),
        new("PREFIX:VOC", "VOC", "حرف نداء", I3rabStatusMapping.Approved, null, 53),
        new("STEM:V:IMPF:ACT:1S", "V.IMPF.ACT", "فعل مضارع", I3rabStatusMapping.Approved, null, 54),
        new("PREFIX:RSLT", "RSLT", "الفاء الرابطة لجواب الشرط", I3rabStatusMapping.Approved, null, 55),
        new("STEM:PN:NOM", "PN.NOM", "اسم علم مرفوع", I3rabStatusMapping.Approved, null, 56),
        new("STEM:PRO", "PRO", "ضمير منفصل", I3rabStatusMapping.Approved, null, 57),
        new("STEM:V:PERF:PASS:3MS", "V.PERF.PASS", "فعل ماض مبني للمجهول", I3rabStatusMapping.Approved, null, 58),
        new("STEM:PN:ACC", "PN.ACC", "اسم علم منصوب", I3rabStatusMapping.Approved, null, 59),
        new("PREFIX:PRP", "PRP", "لام التعليل", I3rabStatusMapping.Approved, null, 60),
        new("PREFIX:CIRC", "CIRC", "واو الحال", I3rabStatusMapping.Approved, null, 61),
        new("SUFFIX:PRON:3FP", "PRON.SUF", "ضمير متصل للغائبات", I3rabStatusMapping.Approved, null, 62),
        new("SUFFIX:EMPH", "EMPH.SUFFIX", "نون التوكيد", I3rabStatusMapping.Approved, null, 63),
        new("STEM:V:PERF:ACT:2MS", "V.PERF.ACT", "فعل ماض", I3rabStatusMapping.Approved, null, 64),
        new("PREFIX:SUP", "SUP", "حرف زائد", I3rabStatusMapping.Approved, null, 65),
        new("STEM:PRON:3FS", "PRON.STEM", "ضمير للغائبة", I3rabStatusMapping.Approved, null, 66),
        new("STEM:V:PERF:ACT:1S", "V.PERF.ACT", "فعل ماض", I3rabStatusMapping.Approved, null, 67),
        new("STEM:V:IMPF:PASS:3MS", "V.IMPF.PASS", "فعل مضارع مبني للمجهول", I3rabStatusMapping.Approved, null, 68),
        new("STEM:PRON:1P", "PRON.STEM", "ضمير لجماعة المتكلمين", I3rabStatusMapping.Approved, null, 69),
        new("STEM:PRON:2MS", "PRON.STEM", "ضمير للمخاطب", I3rabStatusMapping.Approved, null, 70),
        new("STEM:PREV", "PREV", "ما الكافّة", I3rabStatusMapping.Approved, null, 71),
        new("STEM:PRON:1S", "PRON.STEM", "ضمير للمتكلم المفرد", I3rabStatusMapping.Approved, null, 72),
        new("STEM:V:IMPF:PASS:3MP", "V.IMPF.PASS", "فعل مضارع مبني للمجهول", I3rabStatusMapping.Approved, null, 73),
        new("STEM:V:PERF:PASS:3MP", "V.PERF.PASS", "فعل ماض مبني للمجهول", I3rabStatusMapping.Approved, null, 74),
        new("STEM:RET", "RET", "حرف إضراب (بل)", I3rabStatusMapping.Approved, null, 75),
        new("PREFIX:FUT", "FUT.PREFIX", "حرف استقبال", I3rabStatusMapping.Approved, null, 76),
        new("SUFFIX:PRON:3MD", "PRON.SUF", "ضمير متصل للغائبَين", I3rabStatusMapping.Approved, null, 77),
        new("STEM:V:IMPF:PASS:2MP", "V.IMPF.PASS", "فعل مضارع مبني للمجهول", I3rabStatusMapping.Approved, null, 78),
        new("STEM:EXP", "EXP", "أداة استثناء (إلّا)", I3rabStatusMapping.Approved, null, 79),
        new("SUFFIX:PRON:3D", "PRON.SUF", "ضمير متصل للغائبَين", I3rabStatusMapping.Approved, null, 80),
        new("SUFFIX:PRON:2D", "PRON.SUF", "ضمير متصل للمخاطبَين", I3rabStatusMapping.Approved, null, 81),
        new("STEM:V:PERF:PASS:3FS", "V.PERF.PASS", "فعل ماض مبني للمجهول", I3rabStatusMapping.Approved, null, 82),
        new("STEM:INC", "INC", "حرف ابتداء/استفتاح", I3rabStatusMapping.Approved, null, 83),
        new("PREFIX:CAUS", "CAUS", "فاء السببية", I3rabStatusMapping.Approved, null, 84),
        new("PREFIX:IMPV", "IMPV.PREFIX.LAM", "لام الأمر", I3rabStatusMapping.Approved, null, 85),
        new("STEM:EXL", "EXL", "حرف تفصيل", I3rabStatusMapping.Approved, null, 86),
        new("STEM:AMD", "AMD", "حرف استدراك", I3rabStatusMapping.Approved, null, 87),
        new("SUFFIX:PRON:2FS", "PRON.SUF", "ضمير متصل للمخاطبة", I3rabStatusMapping.Approved, null, 88),
        new("STEM:V:IMPF:PASS:3FS", "V.IMPF.PASS", "فعل مضارع مبني للمجهول", I3rabStatusMapping.Approved, null, 89),
        new("STEM:V:IMPF:ACT:2D", "V.IMPF.ACT", "فعل مضارع", I3rabStatusMapping.Approved, null, 90),
        new("STEM:V:IMPF:ACT:3FP", "V.IMPF.ACT", "فعل مضارع", I3rabStatusMapping.Approved, null, 91),
        new("STEM:DEM:2MP", "DEM", "اسم إشارة", I3rabStatusMapping.Approved, null, 92),
        new("STEM:INT", "INT", "حرف تفسير", I3rabStatusMapping.Approved, null, 93),
        new("STEM:FUT", "FUT.STEM", "حرف استقبال", I3rabStatusMapping.Approved, null, 94),
        new("STEM:ANS", "ANS", "حرف جواب", I3rabStatusMapping.Approved, null, 95),
        new("STEM:EXH", "EXH", "حرف تحضيض", I3rabStatusMapping.Approved, null, 96),
        new("STEM:V:PERF:ACT:3MD", "V.PERF.ACT", "فعل ماض", I3rabStatusMapping.Approved, null, 97),
        new("STEM:V:PERF:ACT:3FP", "V.PERF.ACT", "فعل ماض", I3rabStatusMapping.Approved, null, 98),
        new("STEM:V:IMPF:ACT:3MD", "V.IMPF.ACT", "فعل مضارع", I3rabStatusMapping.Approved, null, 99),
        new("STEM:SUR", "SUR", "حرف فجاءة", I3rabStatusMapping.Approved, null, 100),
        new("STEM:AVR", "AVR", "حرف ردع (كلّا)", I3rabStatusMapping.Approved, null, 101),
        new("SUFFIX:PRON:2FP", "PRON.SUF", "ضمير متصل للمخاطبات", I3rabStatusMapping.Approved, null, 102),
        new("STEM:INL", "INL", "حروف مقطّعة (فواتح السور)", I3rabStatusMapping.Approved, null, 103),
        new("STEM:V:PERF:PASS:2MP", "V.PERF.PASS", "فعل ماض مبني للمجهول", I3rabStatusMapping.Approved, null, 104),
        new("STEM:PRON:3FP", "PRON.STEM", "ضمير للغائبات", I3rabStatusMapping.Approved, null, 105),
        new("STEM:V:IMPV:ACT:2FS", "V.IMPV.ACT", "فعل أمر", I3rabStatusMapping.Approved, null, 106),
        new("STEM:V:PERF:PASS:1S", "V.PERF.PASS", "فعل ماض مبني للمجهول", I3rabStatusMapping.Approved, null, 107),
        new("STEM:V:PERF:PASS:1P", "V.PERF.PASS", "فعل ماض مبني للمجهول", I3rabStatusMapping.Approved, null, 108),
        new("SUFFIX:PRON:2MD", "PRON.SUF", "ضمير متصل للمخاطبَين", I3rabStatusMapping.Approved, null, 109),
        new("STEM:SUP", "SUP", "حرف زائد", I3rabStatusMapping.Approved, null, 110),
        new("STEM:PRON:3D", "PRON.STEM", "ضمير للغائبَين", I3rabStatusMapping.Approved, null, 111),
        new("STEM:V:IMPV:ACT:2MD", "V.IMPV.ACT", "فعل أمر", I3rabStatusMapping.Approved, null, 112),
        new("SUFFIX:PRON:3FD", "PRON.SUF", "ضمير متصل للغائبتَين", I3rabStatusMapping.Approved, null, 113),
        new("STEM:V:IMPF:PASS:2MS", "V.IMPF.PASS", "فعل مضارع مبني للمجهول", I3rabStatusMapping.Approved, null, 114),
        new("STEM:V:PERF:ACT:3FD", "V.PERF.ACT", "فعل ماض", I3rabStatusMapping.Approved, null, 115),
        new("STEM:V:IMPV:ACT:2FP", "V.IMPV.ACT", "فعل أمر", I3rabStatusMapping.Approved, null, 116),
        new("STEM:PRON:2D", "PRON.STEM", "ضمير للمخاطبَين", I3rabStatusMapping.Approved, null, 117),
        new("STEM:V:IMPF:ACT:2FS", "V.IMPF.ACT", "فعل مضارع", I3rabStatusMapping.Approved, null, 118),
        new("STEM:V:PERF:PASS:2MS", "V.PERF.PASS", "فعل ماض مبني للمجهول", I3rabStatusMapping.Approved, null, 119),
        new("STEM:V:IMPF:PASS:1P", "V.IMPF.PASS", "فعل مضارع مبني للمجهول", I3rabStatusMapping.Approved, null, 120),
        new("PREFIX:EQ", "EQ", "همزة التسوية", I3rabStatusMapping.Approved, null, 121),
        new("STEM:V:PERF:ACT:2FP", "V.PERF.ACT", "فعل ماض", I3rabStatusMapping.Approved, null, 122),
        new("SUFFIX:VOC", "VOC.SUFFIX", "ميم عوض عن حرف النداء", I3rabStatusMapping.Approved, null, 123),
        new("STEM:V:PERF:ACT:2FS", "V.PERF.ACT", "فعل ماض", I3rabStatusMapping.Approved, null, 124),
        new("STEM:V:IMPV:ACT:2D", "V.IMPV.ACT", "فعل أمر", I3rabStatusMapping.Approved, null, 125),
        new("STEM:V:IMPF:ACT:2FP", "V.IMPF.ACT", "فعل مضارع", I3rabStatusMapping.Approved, null, 126),
        new("STEM:V:IMPF:PASS:1S", "V.IMPF.PASS", "فعل مضارع مبني للمجهول", I3rabStatusMapping.Approved, null, 127),
        new("PREFIX:COM", "COM", "واو المعية", I3rabStatusMapping.Approved, null, 128),
        new("SUFFIX:PRON:2FD", "PRON.SUF", "ضمير متصل للمخاطبتَين", I3rabStatusMapping.Approved, null, 129),
        new("STEM:V:IMPF:PASS:3FP", "V.IMPF.PASS", "فعل مضارع مبني للمجهول", I3rabStatusMapping.Approved, null, 130),
        new("STEM:V:IMPF:ACT:2FD", "V.IMPF.ACT", "فعل مضارع", I3rabStatusMapping.Approved, null, 131),
        new("STEM:IMPN", "IMPN", "اسم فعل أمر", I3rabStatusMapping.Approved, null, 132),
        new("STEM:PRON:2FS", "PRON.STEM", "ضمير للمخاطبة", I3rabStatusMapping.Approved, null, 133),
        new("SUFFIX:P", "P.SUFFIX", "لام الجر", I3rabStatusMapping.Approved, null, 134),
        new("STEM:V:PERF:ACT:2D", "V.PERF.ACT", "فعل ماض", I3rabStatusMapping.Approved, null, 135),
        new("STEM:V:PERF:PASS:3FD", "V.PERF.PASS", "فعل ماض مبني للمجهول", I3rabStatusMapping.Approved, null, 136),
        new("STEM:V:IMPF:PASS:2MD", "V.IMPF.PASS", "فعل مضارع مبني للمجهول", I3rabStatusMapping.Approved, null, 137),
        new("STEM:V:PERF:PASS:3FP", "V.PERF.PASS", "فعل ماض مبني للمجهول", I3rabStatusMapping.Approved, null, 138),
        new("STEM:N:GEN:1S", "N.GEN.1S", "اسم مجرور مضاف إلى ياء المتكلم", I3rabStatusMapping.Approved, null, 139),
        new("STEM:DEM:2FP", "DEM", "اسم إشارة", I3rabStatusMapping.Approved, null, 140),
        new("STEM:DEM:2D", "DEM", "اسم إشارة", I3rabStatusMapping.Approved, null, 141),
        new("STEM:V:IMPF:ACT:3FD", "V.IMPF.ACT", "فعل مضارع", I3rabStatusMapping.Approved, null, 142),
    ];
}
