const bands = require('./src/app/shared/layout/breakpoints.contract.json');

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{html,ts}'],
  theme: {
    extend: {
      screens: {
        compact: { max: `${bands.compactMax}px` },
        medium: { min: `${bands.mediumMin}px`, max: `${bands.mediumMax}px` },
        wide: `${bands.wideMin}px`,
        'wide-plus': `${bands.widePlusMin}px`,
      },
      colors: {
        'qd-bg-page': 'var(--qd-bg-page)',
        'qd-bg-chrome': 'var(--qd-bg-chrome)',
        'qd-surface': 'var(--qd-surface)',
        'qd-surface-quiet': 'var(--qd-surface-quiet)',
        'qd-surface-sunken': 'var(--qd-surface-sunken)',
        'qd-footer-bg': 'var(--qd-footer-bg)',
        'qd-ink': 'var(--qd-ink)',
        'qd-ink-body': 'var(--qd-ink-body)',
        'qd-ink-muted': 'var(--qd-ink-muted)',
        'qd-ink-on-dark': 'var(--qd-ink-on-dark)',
        'qd-green-solid': 'var(--qd-green-solid)',
        'qd-green-text': 'var(--qd-green-text)',
        'qd-green-tint': 'var(--qd-green-tint)',
        'qd-green-thread': 'var(--qd-green-thread)',
        'qd-green-quiet': 'var(--qd-green-quiet)',
        'qd-danger': 'var(--qd-danger)',
        'qd-danger-tint': 'var(--qd-danger-tint)',
        'qd-danger-hairline': 'var(--qd-danger-hairline)',
        'qd-warning': 'var(--qd-warning)',
        'qd-warning-tint': 'var(--qd-warning-tint)',
        'qd-warning-hairline': 'var(--qd-warning-hairline)',
        'qd-neutral': 'var(--qd-neutral)',
        'qd-neutral-tint': 'var(--qd-neutral-tint)',
        'qd-neutral-ink-disabled': 'var(--qd-neutral-ink-disabled)',
        'qd-lifecycle-pending': 'var(--qd-lifecycle-pending)',
        'qd-lifecycle-pending-tint': 'var(--qd-lifecycle-pending-tint)',
        'qd-lifecycle-active': 'var(--qd-lifecycle-active)',
        'qd-lifecycle-active-tint': 'var(--qd-lifecycle-active-tint)',
        'qd-lifecycle-disabled': 'var(--qd-lifecycle-disabled)',
        'qd-lifecycle-disabled-tint': 'var(--qd-lifecycle-disabled-tint)',
        'qd-lifecycle-unknown': 'var(--qd-lifecycle-unknown)',
        'qd-lifecycle-unknown-tint': 'var(--qd-lifecycle-unknown-tint)',
        'qd-mutation-success': 'var(--qd-mutation-success)',
        'qd-mutation-success-tint': 'var(--qd-mutation-success-tint)',
        'qd-membership-owner': 'var(--qd-membership-owner)',
        'qd-hairline': 'var(--qd-border)',
        'qd-hairline-strong': 'var(--qd-border-strong)',
      },
      borderColor: {
        'qd-hairline': 'var(--qd-border)',
        'qd-hairline-strong': 'var(--qd-border-strong)',
      },
      fontFamily: {
        'qd-ui': 'var(--qd-font-ui)',
        'qd-naskh': 'var(--qd-font-naskh)',
        'qd-quran': 'var(--qd-font-quran)',
      },
      fontSize: {
        'qd-caption': ['var(--qd-type-caption)', { lineHeight: 'var(--qd-type-caption-lh)' }],
        'qd-meta': ['var(--qd-type-meta)', { lineHeight: 'var(--qd-type-meta-lh)' }],
        'qd-body': ['var(--qd-type-body)', { lineHeight: 'var(--qd-type-body-lh)' }],
        'qd-body-lg': ['var(--qd-type-body-lg)', { lineHeight: 'var(--qd-type-body-lg-lh)' }],
        'qd-h4': ['var(--qd-type-h4)', { lineHeight: 'var(--qd-type-h4-lh)' }],
        'qd-h3': ['var(--qd-type-h3)', { lineHeight: 'var(--qd-type-h3-lh)' }],
        'qd-h2': ['var(--qd-type-h2)', { lineHeight: 'var(--qd-type-h2-lh)' }],
        'qd-h1': ['var(--qd-type-h1)', { lineHeight: 'var(--qd-type-h1-lh)' }],
        'qd-identity': ['var(--qd-type-identity)', { lineHeight: 'var(--qd-type-identity-lh)' }],
      },
      spacing: {
        'qd-2': 'var(--qd-s-2)',
        'qd-4': 'var(--qd-s-4)',
        'qd-8': 'var(--qd-s-8)',
        'qd-12': 'var(--qd-s-12)',
        'qd-16': 'var(--qd-s-16)',
        'qd-20': 'var(--qd-s-20)',
        'qd-24': 'var(--qd-s-24)',
        'qd-32': 'var(--qd-s-32)',
        'qd-40': 'var(--qd-s-40)',
        'qd-48': 'var(--qd-s-48)',
        'qd-64': 'var(--qd-s-64)',
        'qd-gutter': 'var(--qd-page-gutter)',
        'qd-rhythm': 'var(--qd-page-rhythm)',
      },
      borderRadius: {
        'qd-xs': 'var(--qd-radius-xs)',
        'qd-sm': 'var(--qd-radius-sm)',
        'qd-md': 'var(--qd-radius-md)',
        'qd-lg': 'var(--qd-radius-lg)',
        'qd-pill': 'var(--qd-radius-pill)',
      },
      boxShadow: {
        'qd-layer': 'var(--qd-shadow-layer)',
        'qd-none': 'none',
      },
      maxWidth: {
        'qd-capped-reading': 'var(--qd-page-measure-capped-reading)',
        'qd-full-data': 'var(--qd-page-measure-full-data)',
        'qd-split-workspace': 'var(--qd-page-measure-split-workspace)',
        'qd-protected-mushaf': 'var(--qd-page-measure-protected-mushaf)',
        'qd-medium-ceiling': 'var(--qd-page-measure-medium-ceiling)',
        'qd-prose': 'var(--qd-measure-prose)',
        'qd-page-description': 'var(--qd-measure-page-description)',
        'qd-modal-confirm': 'var(--qd-modal-confirm)',
        'qd-modal-form': 'var(--qd-modal-form)',
        'qd-modal-wide': 'var(--qd-modal-wide)',
        'qd-modal-overlay': 'var(--qd-modal-overlay)',
      },
      width: {
        'qd-rail-s': 'var(--qd-rail-s)',
        'qd-rail-m': 'var(--qd-rail-m)',
        'qd-rail-l': 'var(--qd-rail-l)',
        'qd-pagination-jump': 'var(--qd-pagination-jump-inline-size)',
      },
      height: {
        'qd-control-sm': 'var(--qd-control-sm)',
        'qd-control-md': 'var(--qd-control-md)',
        'qd-control-lg': 'var(--qd-control-lg)',
        'qd-hit-target': 'var(--qd-hit-target-min)',
      },
      minHeight: {
        'qd-hit-target': 'var(--qd-hit-target-min)',
      },
      minWidth: {
        'qd-hit-target': 'var(--qd-hit-target-min)',
      },
      gridTemplateColumns: {
        'qd-split-data': 'var(--qd-split-data)',
        'qd-split-mushaf': 'var(--qd-split-mushaf)',
        'qd-destinations':
          'repeat(auto-fit, minmax(min(100%, var(--qd-grid-destinations-min)), 1fr))',
        'qd-curriculum': 'repeat(auto-fit, minmax(min(100%, var(--qd-grid-curriculum-min)), 1fr))',
        'qd-doors': 'repeat(auto-fit, minmax(min(100%, var(--qd-grid-doors-min)), 1fr))',
        'qd-permission-groups':
          'repeat(auto-fit, minmax(min(100%, var(--qd-grid-permission-groups-min)), 1fr))',
      },
      transitionDuration: {
        'qd-state': '140ms',
      },
      zIndex: {
        'qd-sticky': 'var(--qd-z-sticky)',
        'qd-popover': 'var(--qd-z-popover)',
        'qd-floating': 'var(--qd-z-floating)',
        'qd-mobile-nav': 'var(--qd-z-mobile-nav)',
        'qd-menu-backdrop': 'var(--qd-z-menu-backdrop)',
        'qd-menu': 'var(--qd-z-menu)',
        'qd-modal-backdrop': 'var(--qd-z-modal-backdrop)',
        'qd-modal': 'var(--qd-z-modal)',
        'qd-nav-progress': 'var(--qd-z-nav-progress)',
      },
    },
  },
  plugins: [],
};
