export const LINKING_LABELS = {
  workspace: 'مساحة الربط',
  preparedSources: 'المصادر المُعَدَّة',
  directLink: 'ربط مباشر',
  directLinkSource: 'مصدر الربط',
  directLinkSteps: {
    door: 'اختيار الباب',
    ayahs: 'اختيار الآيات',
    highlight: 'الإبراز',
    review: 'المراجعة',
    result: 'النتيجة',
  },
  chooseDoor: 'اختر الباب',
  chooseDoorHint: 'اختر باباً واحداً من الأبواب المتاحة لإتمام الربط.',
  doorsEmpty: 'لا توجد أبواب متاحة للاختيار.',
  searchDoors: 'ابحث في الأبواب',
  selectedDoorUnavailable: 'الباب المحدد لم يعد متاحاً. اختر باباً آخر.',
  next: 'التالي',
  back: 'رجوع',
  sourceLoading: 'يجري تحميل جميع آيات المصدر',
  sourceReady: 'اكتمل تحميل آيات المصدر',
  sourceLoadError: 'تعذر تحميل نتائج المصدر كاملة.',
  retry: 'إعادة المحاولة',
  selectAyahs: 'اختيار الآيات',
  searchAyahs: 'ابحث في الآيات',
  noAyahMatches: 'لا توجد آيات مطابقة للبحث.',
  selectAll: 'تحديد الكل',
  clearAll: 'إلغاء تحديد الكل',
  highlightStep: 'إبراز كلمات المصدر',
  highlightDescription: 'أبرز كلمات المصدر داخل نص الآيات.',
  reviewTitle: 'مراجعة الربط',
  reviewTarget: 'الباب المستهدف',
  reviewSelection: 'الآيات المختارة من إجمالي النتائج',
  reviewIndependent: 'كل آية ستُربط بالباب بصورة مستقلة.',
  reviewHighlight: 'إبراز كلمات المصدر',
  confirm: 'تأكيد الربط',
  close: 'إغلاق',
  sourceUnsupported: 'هذا المصدر غير مدعوم في الربط المباشر بعد.',
  addedToWorkspace: 'أُضيف المصدر إلى مساحة الربط.',
  alreadyInWorkspace: 'المصدر موجود بالفعل في مساحة الربط.',
  addToWorkspace: 'إضافة للربط',
  editSelection: 'تعديل اختيار الآيات',
  sourceEditor: 'تعديل اختيار الآيات',
  sourceEditorBack: 'العودة إلى مساحة الربط',
  sourceEditorLoading: 'يجري تحميل آيات المصدر كاملة',
  sourceEditorReady: 'آية متاحة للاختيار',
  sourceEditorPreviousCount: 'العدد السابق يحتاج إلى تحديث',
  sourceEditorUnsupported: 'لا يمكن تحرير هذا المصدر قبل اكتمال مصدر المصحف اليدوي.',
  sourceEditorPagination: 'صفحات آيات المصدر',
  removeSource: 'إزالة المصدر',
  emptyWorkspace: 'لم تُضف مصادر للربط بعد.',
  unresolvedResultCount: 'لم تُحمّل النتائج بعد',
  resultCount: 'عدد النتائج',
  selectedCount: 'الآيات المختارة',
  highlightSourceWords: 'إبراز كلمات المصدر',
  highlightEnabled: 'مفعّل',
  highlightDisabled: 'متوقف',
  success: 'تم الربط بنجاح',
  sourceKinds: {
    'manual-mushaf-ayahs': 'آيات من المصحف',
    'unique-word': 'كلمة فريدة',
    root: 'جذر',
    lemma: 'الصيغة المعجمية',
    stem: 'الأصل الصرفي',
    'word-type': 'نوع كلمة',
  },
} as const;
