export const LINKING_LABELS = {
  workspace: 'مساحة الربط',
  preparedSources: 'المصادر المُعَدَّة',
  directLink: 'ربط مباشر',
  directLinkSource: 'مصدر الربط',
  directLinkSteps: {
    door: 'اختيار الباب',
    ayahs: 'اختيار الآيات',
    highlight: 'الإبراز',
    review: 'المراجعة',
    result: 'النتيجة',
  },
  chooseDoor: 'اختر الباب',
  chooseDoorHint: 'اختر باباً واحداً من الأبواب المتاحة لإتمام الربط.',
  doorsEmpty: 'لا توجد أبواب متاحة للاختيار.',
  searchDoors: 'ابحث في الأبواب',
  selectedDoorUnavailable: 'الباب المحدد لم يعد متاحاً. اختر باباً آخر.',
  next: 'التالي',
  back: 'رجوع',
  sourceLoading: 'يجري تحميل جميع آيات المصدر',
  sourceReady: 'اكتمل تحميل آيات المصدر',
  sourceLoadError: 'تعذر تحميل نتائج المصدر كاملة.',
  retry: 'إعادة المحاولة',
  sourceUnsupported: 'هذا المصدر غير مدعوم في الربط المباشر بعد.',
  addedToWorkspace: 'أُضيف المصدر إلى مساحة الربط.',
  alreadyInWorkspace: 'المصدر موجود بالفعل في مساحة الربط.',
  addToWorkspace: 'إضافة للربط',
  editSelection: 'تعديل اختيار الآيات',
  removeSource: 'إزالة المصدر',
  emptyWorkspace: 'لم تُضف مصادر للربط بعد.',
  unresolvedResultCount: 'لم تُحمّل النتائج بعد',
  resultCount: 'عدد النتائج',
  selectedCount: 'الآيات المختارة',
  highlightSourceWords: 'إبراز كلمات المصدر',
  highlightEnabled: 'مفعّل',
  highlightDisabled: 'متوقف',
  success: 'تم الربط بنجاح',
  sourceKinds: {
    'mushaf-word': 'كلمة من المصحف',
    'unique-word': 'كلمة فريدة',
    root: 'جذر',
    lemma: 'أصل',
    stem: 'صيغة',
    'word-type': 'نوع كلمة',
  },
} as const;
