export const LINKING_LABELS = {
  workspace: 'مساحة الربط',
  preparedSources: 'المصادر المُعَدَّة',
  directLink: 'ربط مباشر',
  addToWorkspace: 'إضافة للربط',
  editSelection: 'تعديل اختيار الآيات',
  removeSource: 'إزالة المصدر',
  emptyWorkspace: 'لم تُضف مصادر للربط بعد.',
  unresolvedResultCount: 'لم تُحمّل النتائج بعد',
  resultCount: 'عدد النتائج',
  selectedCount: 'الآيات المختارة',
  highlightSourceWords: 'إبراز كلمات المصدر',
  highlightEnabled: 'مفعّل',
  highlightDisabled: 'متوقف',
  success: 'تم الربط بنجاح',
  sourceKinds: {
    'mushaf-word': 'كلمة من المصحف',
    'unique-word': 'كلمة فريدة',
    root: 'جذر',
    lemma: 'أصل',
    stem: 'صيغة',
    'word-type': 'نوع كلمة',
  },
} as const;
