// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QuranDashboard.Infrastructure.Persistence;

#nullable disable

namespace QuranDashboard.Infrastructure.Migrations
{
    [DbContext(typeof(QuranDashboardDbContext))]
    [Migration("20260621181644_DeterministicUniqueWordIds")]
    partial class DeterministicUniqueWordIds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QuranDashboard.Domain.Quran.Ayahs.Ayah", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<short>("AyahNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("ayah_number");

                    b.Property<short?>("HizbNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("hizb_number");

                    b.Property<short?>("JuzNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("juz_number");

                    b.Property<short>("PageFrom")
                        .HasColumnType("smallint")
                        .HasColumnName("page_from");

                    b.Property<short>("PageTo")
                        .HasColumnType("smallint")
                        .HasColumnName("page_to");

                    b.Property<short?>("RubNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("rub_number");

                    b.Property<short>("SurahNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("surah_number");

                    b.Property<string>("TextUthmani")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text_uthmani");

                    b.Property<string>("VerseKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("verse_key");

                    b.Property<short>("WordsCountReal")
                        .HasColumnType("smallint")
                        .HasColumnName("words_count_real");

                    b.Property<short>("WordsCountSource")
                        .HasColumnType("smallint")
                        .HasColumnName("words_count_source");

                    b.HasKey("Id");

                    b.HasIndex("HizbNumber");

                    b.HasIndex("JuzNumber");

                    b.HasIndex("RubNumber");

                    b.HasIndex("VerseKey")
                        .IsUnique();

                    b.HasIndex("SurahNumber", "AyahNumber")
                        .IsUnique();

                    b.ToTable("quran_ayahs", (string)null);
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.FullI3rab.FullI3rabAyahEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AyahId")
                        .HasColumnType("integer")
                        .HasColumnName("ayah_id");

                    b.Property<long>("EntryId")
                        .HasColumnType("bigint")
                        .HasColumnName("entry_id");

                    b.Property<bool>("IsGroupLeader")
                        .HasColumnType("boolean")
                        .HasColumnName("is_group_leader");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<int>("SourceId")
                        .HasColumnType("integer")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceLeaderVerseKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_leader_verse_key");

                    b.Property<string>("SourceValueKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_value_kind");

                    b.Property<string>("VerseKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("verse_key");

                    b.HasKey("Id");

                    b.HasIndex("EntryId");

                    b.HasIndex("AyahId", "SourceId");

                    b.HasIndex("SourceId", "AyahId")
                        .IsUnique();

                    b.HasIndex("SourceId", "VerseKey")
                        .IsUnique();

                    b.ToTable("quran_full_i3rab_ayah_entries", null, t =>
                        {
                            t.HasCheckConstraint("CK_quran_full_i3rab_ayah_entries_source_value_kind", "source_value_kind IN ('leader', 'member_pointer', 'flat')");
                        });
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.FullI3rab.FullI3rabEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<short>("CoveredAyahCount")
                        .HasColumnType("smallint")
                        .HasColumnName("covered_ayah_count");

                    b.Property<string>("CoveredAyahKeys")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("covered_ayah_keys");

                    b.Property<string>("I3rabHtml")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("i3rab_html");

                    b.Property<int>("LeaderAyahId")
                        .HasColumnType("integer")
                        .HasColumnName("leader_ayah_id");

                    b.Property<string>("SourceEntryKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_entry_key");

                    b.Property<int>("SourceId")
                        .HasColumnType("integer")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceShape")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_shape");

                    b.Property<string>("TextHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text_hash");

                    b.HasKey("Id");

                    b.HasIndex("LeaderAyahId");

                    b.HasIndex("SourceId", "LeaderAyahId");

                    b.HasIndex("SourceId", "SourceEntryKey")
                        .IsUnique();

                    b.ToTable("quran_full_i3rab_entries", null, t =>
                        {
                            t.HasCheckConstraint("CK_quran_full_i3rab_entries_covered_ayah_count", "covered_ayah_count >= 1");

                            t.HasCheckConstraint("CK_quran_full_i3rab_entries_i3rab_html", "i3rab_html <> ''");

                            t.HasCheckConstraint("CK_quran_full_i3rab_entries_source_shape", "source_shape IN ('grouped_leader', 'flat')");
                        });
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.FullI3rab.FullI3rabSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short>("ContentCoverageCount")
                        .HasColumnType("smallint")
                        .HasColumnName("content_coverage_count");

                    b.Property<string>("ContributorNameAr")
                        .HasColumnType("text")
                        .HasColumnName("contributor_name_ar");

                    b.Property<string>("ContributorNameEn")
                        .HasColumnType("text")
                        .HasColumnName("contributor_name_en");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("direction");

                    b.Property<string>("DisplayNameAr")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name_ar");

                    b.Property<string>("DisplayNameEn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name_en");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<bool>("HasQuranQuotationMarkup")
                        .HasColumnType("boolean")
                        .HasColumnName("has_quran_quotation_markup");

                    b.Property<DateTimeOffset>("ImportedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("imported_at_utc");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("language_code");

                    b.Property<string>("LicenseStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("license_status");

                    b.Property<string>("ManifestMetadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("manifest_metadata");

                    b.Property<string>("MarkupFormat")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("markup_format");

                    b.Property<string>("PackageFile")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("package_file");

                    b.Property<string>("ProvenanceStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provenance_status");

                    b.Property<string>("ResourceKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("resource_kind");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sha256");

                    b.Property<string>("ShortNameAr")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("short_name_ar");

                    b.Property<string>("ShortNameEn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("short_name_en");

                    b.Property<string>("SourceFileOriginal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_file_original");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_key");

                    b.Property<string>("UsageScope")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usage_scope");

                    b.HasKey("Id");

                    b.HasIndex("PackageFile")
                        .IsUnique();

                    b.HasIndex("SourceKey")
                        .IsUnique();

                    b.ToTable("quran_full_i3rab_sources", null, t =>
                        {
                            t.HasCheckConstraint("CK_quran_full_i3rab_sources_content_coverage_count", "content_coverage_count = 6236");

                            t.HasCheckConstraint("CK_quran_full_i3rab_sources_direction", "direction IN ('rtl', 'ltr')");

                            t.HasCheckConstraint("CK_quran_full_i3rab_sources_language_code", "language_code = 'ar'");

                            t.HasCheckConstraint("CK_quran_full_i3rab_sources_license_status", "license_status = 'unknown'");

                            t.HasCheckConstraint("CK_quran_full_i3rab_sources_markup_format", "markup_format = 'html'");

                            t.HasCheckConstraint("CK_quran_full_i3rab_sources_provenance_status", "provenance_status = 'unknown'");

                            t.HasCheckConstraint("CK_quran_full_i3rab_sources_resource_kind", "resource_kind = 'full_i3rab'");

                            t.HasCheckConstraint("CK_quran_full_i3rab_sources_usage_scope", "usage_scope = 'internal-only-until-cleared'");
                        });
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.MushafPages.MushafLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("FirstWordId")
                        .HasColumnType("integer")
                        .HasColumnName("first_word_id");

                    b.Property<bool>("IsCentered")
                        .HasColumnType("boolean")
                        .HasColumnName("is_centered");

                    b.Property<int?>("LastWordId")
                        .HasColumnType("integer")
                        .HasColumnName("last_word_id");

                    b.Property<short>("LineNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("line_number");

                    b.Property<string>("LineType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("line_type");

                    b.Property<short>("PageNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("page_number");

                    b.Property<short?>("SurahNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("surah_number");

                    b.Property<short>("WordsCount")
                        .HasColumnType("smallint")
                        .HasColumnName("words_count");

                    b.HasKey("Id");

                    b.HasIndex("FirstWordId");

                    b.HasIndex("LastWordId");

                    b.HasIndex("SurahNumber");

                    b.HasIndex("PageNumber", "LineNumber")
                        .IsUnique();

                    b.ToTable("quran_mushaf_lines", (string)null);
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.MushafPages.MushafPage", b =>
                {
                    b.Property<short>("PageNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("page_number");

                    b.Property<short>("FirstAyahNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("first_ayah_number");

                    b.Property<short>("FirstSurahNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("first_surah_number");

                    b.Property<short>("LastAyahNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("last_ayah_number");

                    b.Property<short>("LastSurahNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("last_surah_number");

                    b.Property<short>("LinesCount")
                        .HasColumnType("smallint")
                        .HasColumnName("lines_count");

                    b.HasKey("PageNumber");

                    b.ToTable("quran_mushaf_pages", (string)null);
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.Mutashabihat.MutashabihatGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short>("DistinctAyahCount")
                        .HasColumnType("smallint")
                        .HasColumnName("distinct_ayah_count");

                    b.Property<short>("DistinctSurahCount")
                        .HasColumnType("smallint")
                        .HasColumnName("distinct_surah_count");

                    b.Property<short>("OccurrenceCount")
                        .HasColumnType("smallint")
                        .HasColumnName("occurrence_count");

                    b.Property<string>("RawSourceCounts")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_source_counts");

                    b.Property<int>("RepresentativeAyahId")
                        .HasColumnType("integer")
                        .HasColumnName("representative_ayah_id");

                    b.Property<short>("RepresentativeWordFrom")
                        .HasColumnType("smallint")
                        .HasColumnName("representative_word_from");

                    b.Property<short>("RepresentativeWordTo")
                        .HasColumnType("smallint")
                        .HasColumnName("representative_word_to");

                    b.Property<int>("SourceGroupId")
                        .HasColumnType("integer")
                        .HasColumnName("source_group_id");

                    b.HasKey("Id");

                    b.HasIndex("RepresentativeAyahId");

                    b.HasIndex("SourceGroupId")
                        .IsUnique();

                    b.ToTable("quran_mutashabihat_groups", (string)null);
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.Mutashabihat.MutashabihatOccurrence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AyahId")
                        .HasColumnType("integer")
                        .HasColumnName("ayah_id");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<bool>("IsRepresentative")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_representative");

                    b.Property<short>("WordFrom")
                        .HasColumnType("smallint")
                        .HasColumnName("word_from");

                    b.Property<short>("WordTo")
                        .HasColumnType("smallint")
                        .HasColumnName("word_to");

                    b.HasKey("Id");

                    b.HasIndex("AyahId");

                    b.HasIndex("GroupId", "AyahId", "WordFrom", "WordTo")
                        .IsUnique();

                    b.ToTable("quran_mutashabihat_occurrences", (string)null);
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.Mutashabihat.SimilarAyahLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short>("Coverage")
                        .HasColumnType("smallint")
                        .HasColumnName("coverage");

                    b.Property<string>("MatchWords")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("match_words");

                    b.Property<short>("MatchedWordsCount")
                        .HasColumnType("smallint")
                        .HasColumnName("matched_words_count");

                    b.Property<short>("Score")
                        .HasColumnType("smallint")
                        .HasColumnName("score");

                    b.Property<int>("SourceAyahId")
                        .HasColumnType("integer")
                        .HasColumnName("source_ayah_id");

                    b.Property<int>("TargetAyahId")
                        .HasColumnType("integer")
                        .HasColumnName("target_ayah_id");

                    b.HasKey("Id");

                    b.HasIndex("TargetAyahId");

                    b.HasIndex("SourceAyahId", "TargetAyahId")
                        .IsUnique();

                    b.ToTable("quran_similar_ayah_links", null, t =>
                        {
                            t.HasCheckConstraint("CK_quran_similar_ayah_links_no_self", "source_ayah_id <> target_ayah_id");
                        });
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.Navigation.Hizb", b =>
                {
                    b.Property<short>("HizbNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("hizb_number");

                    b.Property<int>("FirstAyahId")
                        .HasColumnType("integer")
                        .HasColumnName("first_ayah_id");

                    b.Property<string>("FirstVerseKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_verse_key");

                    b.Property<short>("JuzNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("juz_number");

                    b.Property<int>("LastAyahId")
                        .HasColumnType("integer")
                        .HasColumnName("last_ayah_id");

                    b.Property<string>("LastVerseKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_verse_key");

                    b.Property<short>("VersesCount")
                        .HasColumnType("smallint")
                        .HasColumnName("verses_count");

                    b.HasKey("HizbNumber");

                    b.HasIndex("FirstAyahId");

                    b.HasIndex("JuzNumber");

                    b.HasIndex("LastAyahId");

                    b.ToTable("quran_hizbs", (string)null);
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.Navigation.Juz", b =>
                {
                    b.Property<short>("JuzNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("juz_number");

                    b.Property<int>("FirstAyahId")
                        .HasColumnType("integer")
                        .HasColumnName("first_ayah_id");

                    b.Property<string>("FirstVerseKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_verse_key");

                    b.Property<int>("LastAyahId")
                        .HasColumnType("integer")
                        .HasColumnName("last_ayah_id");

                    b.Property<string>("LastVerseKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_verse_key");

                    b.Property<short>("VersesCount")
                        .HasColumnType("smallint")
                        .HasColumnName("verses_count");

                    b.HasKey("JuzNumber");

                    b.HasIndex("FirstAyahId");

                    b.HasIndex("LastAyahId");

                    b.ToTable("quran_juzs", (string)null);
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.Navigation.Rub", b =>
                {
                    b.Property<short>("RubNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("rub_number");

                    b.Property<int>("FirstAyahId")
                        .HasColumnType("integer")
                        .HasColumnName("first_ayah_id");

                    b.Property<string>("FirstVerseKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_verse_key");

                    b.Property<short>("HizbNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("hizb_number");

                    b.Property<int>("LastAyahId")
                        .HasColumnType("integer")
                        .HasColumnName("last_ayah_id");

                    b.Property<string>("LastVerseKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_verse_key");

                    b.Property<short>("VersesCount")
                        .HasColumnType("smallint")
                        .HasColumnName("verses_count");

                    b.HasKey("RubNumber");

                    b.HasIndex("FirstAyahId");

                    b.HasIndex("HizbNumber");

                    b.HasIndex("LastAyahId");

                    b.ToTable("quran_rubs", (string)null);
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.Navigation.Sajda", b =>
                {
                    b.Property<short>("SajdahNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("sajdah_number");

                    b.Property<int>("AyahId")
                        .HasColumnType("integer")
                        .HasColumnName("ayah_id");

                    b.Property<string>("SajdahType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sajdah_type");

                    b.Property<string>("VerseKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("verse_key");

                    b.HasKey("SajdahNumber");

                    b.HasIndex("AyahId")
                        .IsUnique();

                    b.ToTable("quran_sajdas", (string)null);
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.Surahs.Surah", b =>
                {
                    b.Property<short>("SurahNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("surah_number");

                    b.Property<bool>("BismillahPre")
                        .HasColumnType("boolean")
                        .HasColumnName("bismillah_pre");

                    b.Property<string>("NameArabic")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_arabic");

                    b.Property<string>("NameSimple")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_simple");

                    b.Property<string>("NameTransliteration")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_transliteration");

                    b.Property<short>("RevelationOrder")
                        .HasColumnType("smallint")
                        .HasColumnName("revelation_order");

                    b.Property<string>("RevelationPlace")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("revelation_place");

                    b.Property<short>("VersesCount")
                        .HasColumnType("smallint")
                        .HasColumnName("verses_count");

                    b.HasKey("SurahNumber");

                    b.HasIndex("NameArabic")
                        .IsUnique();

                    b.ToTable("quran_surahs", (string)null);
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.Tafsirs.TafsirAyahEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AyahId")
                        .HasColumnType("integer")
                        .HasColumnName("ayah_id");

                    b.Property<bool>("IsGroupLeader")
                        .HasColumnType("boolean")
                        .HasColumnName("is_group_leader");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<int>("SourceId")
                        .HasColumnType("integer")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceLeaderVerseKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_leader_verse_key");

                    b.Property<string>("SourceValueKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_value_kind");

                    b.Property<long>("TafsirEntryId")
                        .HasColumnType("bigint")
                        .HasColumnName("tafsir_entry_id");

                    b.Property<string>("VerseKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("verse_key");

                    b.HasKey("Id");

                    b.HasIndex("TafsirEntryId");

                    b.HasIndex("AyahId", "SourceId");

                    b.HasIndex("SourceId", "AyahId")
                        .IsUnique();

                    b.HasIndex("SourceId", "VerseKey")
                        .IsUnique();

                    b.ToTable("quran_tafsir_ayah_entries", null, t =>
                        {
                            t.HasCheckConstraint("CK_quran_tafsir_ayah_entries_source_value_kind", "source_value_kind IN ('leader', 'member_pointer', 'flat')");
                        });
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.Tafsirs.TafsirEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<short>("CoveredAyahCount")
                        .HasColumnType("smallint")
                        .HasColumnName("covered_ayah_count");

                    b.Property<string>("CoveredAyahKeys")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("covered_ayah_keys");

                    b.Property<int>("LeaderAyahId")
                        .HasColumnType("integer")
                        .HasColumnName("leader_ayah_id");

                    b.Property<string>("SourceEntryKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_entry_key");

                    b.Property<int>("SourceId")
                        .HasColumnType("integer")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceShape")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_shape");

                    b.Property<string>("TafsirText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tafsir_text");

                    b.Property<string>("TextHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text_hash");

                    b.HasKey("Id");

                    b.HasIndex("LeaderAyahId");

                    b.HasIndex("SourceId", "LeaderAyahId");

                    b.HasIndex("SourceId", "SourceEntryKey")
                        .IsUnique();

                    b.ToTable("quran_tafsir_entries", null, t =>
                        {
                            t.HasCheckConstraint("CK_quran_tafsir_entries_covered_ayah_count", "covered_ayah_count >= 1");

                            t.HasCheckConstraint("CK_quran_tafsir_entries_source_shape", "source_shape IN ('grouped_leader', 'flat')");

                            t.HasCheckConstraint("CK_quran_tafsir_entries_tafsir_text", "tafsir_text <> ''");
                        });
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.Tafsirs.TafsirSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short>("ContentCoverageCount")
                        .HasColumnType("smallint")
                        .HasColumnName("content_coverage_count");

                    b.Property<string>("ContributorKey")
                        .HasColumnType("text")
                        .HasColumnName("contributor_key");

                    b.Property<string>("ContributorNameAr")
                        .HasColumnType("text")
                        .HasColumnName("contributor_name_ar");

                    b.Property<string>("ContributorNameEn")
                        .HasColumnType("text")
                        .HasColumnName("contributor_name_en");

                    b.Property<string>("ContributorType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contributor_type");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("direction");

                    b.Property<string>("DisplayNameAr")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name_ar");

                    b.Property<string>("DisplayNameEn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name_en");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<DateTimeOffset>("ImportedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("imported_at_utc");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("language_code");

                    b.Property<string>("LanguageNameAr")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("language_name_ar");

                    b.Property<string>("LanguageNameEn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("language_name_en");

                    b.Property<string>("LicenseStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("license_status");

                    b.Property<string>("ManifestMetadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("manifest_metadata");

                    b.Property<string>("PackageFile")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("package_file");

                    b.Property<string>("ProvenanceStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provenance_status");

                    b.Property<string>("ResourceKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("resource_kind");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sha256");

                    b.Property<string>("ShortNameAr")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("short_name_ar");

                    b.Property<string>("ShortNameEn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("short_name_en");

                    b.Property<string>("SourceFileOriginal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_file_original");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_key");

                    b.Property<string>("TafsirKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tafsir_kind");

                    b.HasKey("Id");

                    b.HasIndex("LanguageCode");

                    b.HasIndex("PackageFile")
                        .IsUnique();

                    b.HasIndex("SourceKey")
                        .IsUnique();

                    b.HasIndex("LanguageCode", "TafsirKind");

                    b.ToTable("quran_tafsir_sources", null, t =>
                        {
                            t.HasCheckConstraint("CK_quran_tafsir_sources_content_coverage_count", "content_coverage_count = 6236");

                            t.HasCheckConstraint("CK_quran_tafsir_sources_direction", "direction IN ('rtl', 'ltr')");

                            t.HasCheckConstraint("CK_quran_tafsir_sources_resource_kind", "resource_kind = 'tafsir'");
                        });
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.Translations.TranslationAyahEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AyahId")
                        .HasColumnType("integer")
                        .HasColumnName("ayah_id");

                    b.Property<int>("SourceId")
                        .HasColumnType("integer")
                        .HasColumnName("source_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<string>("VerseKey")
                        .HasColumnType("text")
                        .HasColumnName("verse_key");

                    b.HasKey("Id");

                    b.HasIndex("AyahId", "SourceId");

                    b.HasIndex("SourceId", "AyahId")
                        .IsUnique();

                    b.ToTable("quran_translation_ayah_entries", null, t =>
                        {
                            t.HasCheckConstraint("CK_quran_translation_ayah_entries_text", "text <> ''");
                        });
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.Translations.TranslationSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("ContainsHtmlMarkup")
                        .HasColumnType("boolean")
                        .HasColumnName("contains_html_markup");

                    b.Property<bool>("ContainsInlineFootnotes")
                        .HasColumnType("boolean")
                        .HasColumnName("contains_inline_footnotes");

                    b.Property<short>("ContentCoverageCount")
                        .HasColumnType("smallint")
                        .HasColumnName("content_coverage_count");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("direction");

                    b.Property<string>("DisplayNameAr")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name_ar");

                    b.Property<string>("DisplayNameEn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name_en");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("language_code");

                    b.Property<string>("LanguageNameAr")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("language_name_ar");

                    b.Property<string>("LanguageNameEn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("language_name_en");

                    b.Property<string>("NativeName")
                        .HasColumnType("text")
                        .HasColumnName("native_name");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_key");

                    b.Property<string>("TranslationType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("translation_type");

                    b.Property<string>("TranslatorKey")
                        .HasColumnType("text")
                        .HasColumnName("translator_key");

                    b.Property<string>("TranslatorNameAr")
                        .HasColumnType("text")
                        .HasColumnName("translator_name_ar");

                    b.Property<string>("TranslatorNameEn")
                        .HasColumnType("text")
                        .HasColumnName("translator_name_en");

                    b.HasKey("Id");

                    b.HasIndex("LanguageCode");

                    b.HasIndex("SourceKey")
                        .IsUnique();

                    b.HasIndex("LanguageCode", "TranslationType");

                    b.ToTable("quran_translation_sources", null, t =>
                        {
                            t.HasCheckConstraint("CK_quran_translation_sources_content_coverage_count", "content_coverage_count = 6236");

                            t.HasCheckConstraint("CK_quran_translation_sources_direction", "direction IN ('rtl', 'ltr')");

                            t.HasCheckConstraint("CK_quran_translation_sources_required_fields", "btrim(source_key) <> '' AND\nbtrim(language_code) <> '' AND\nbtrim(language_name_en) <> '' AND\nbtrim(language_name_ar) <> '' AND\nbtrim(direction) <> '' AND\nbtrim(translation_type) <> '' AND\nbtrim(display_name_en) <> '' AND\nbtrim(display_name_ar) <> ''");

                            t.HasCheckConstraint("CK_quran_translation_sources_translation_type", "translation_type IN ('simple', 'with_footnotes')");
                        });
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.Words.Display.OrderedSimpleWord", b =>
                {
                    b.Property<int>("WordOrderInMushaf")
                        .HasColumnType("integer")
                        .HasColumnName("word_order_in_mushaf");

                    b.Property<short>("AyahNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("ayah_number");

                    b.Property<short>("AyahsCount")
                        .HasColumnType("smallint")
                        .HasColumnName("ayahs_count");

                    b.Property<short>("LineNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("line_number");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<int>("OccurrencesCount")
                        .HasColumnType("integer")
                        .HasColumnName("occurrences_count");

                    b.Property<short>("PageNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("page_number");

                    b.Property<int>("QuranWordId")
                        .HasColumnType("integer")
                        .HasColumnName("quran_word_id");

                    b.Property<short>("SurahNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("surah_number");

                    b.Property<short>("SurahsCount")
                        .HasColumnType("smallint")
                        .HasColumnName("surahs_count");

                    b.Property<string>("TextImlaeiSimple")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text_imlaei_simple");

                    b.Property<string>("TextUthmaniSimple")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text_uthmani_simple");

                    b.Property<string>("VerseKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("verse_key");

                    b.Property<string>("WordKeyImlaeiSimple")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("word_key_imlaei_simple");

                    b.Property<short>("WordOrderInAyah")
                        .HasColumnType("smallint")
                        .HasColumnName("word_order_in_ayah");

                    b.Property<short>("WordOrderInSurah")
                        .HasColumnType("smallint")
                        .HasColumnName("word_order_in_surah");

                    b.HasKey("WordOrderInMushaf");

                    b.HasIndex("QuranWordId")
                        .IsUnique();

                    b.HasIndex("SurahNumber", "WordOrderInSurah");

                    b.HasIndex("SurahNumber", "AyahNumber", "WordOrderInAyah");

                    b.ToTable("quran_words_ordered_simple", (string)null);
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.Words.Display.OrderedTashkeelWord", b =>
                {
                    b.Property<int>("WordOrderInMushaf")
                        .HasColumnType("integer")
                        .HasColumnName("word_order_in_mushaf");

                    b.Property<short>("AyahNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("ayah_number");

                    b.Property<short>("AyahsCount")
                        .HasColumnType("smallint")
                        .HasColumnName("ayahs_count");

                    b.Property<short>("LineNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("line_number");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<int>("OccurrencesCount")
                        .HasColumnType("integer")
                        .HasColumnName("occurrences_count");

                    b.Property<short>("PageNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("page_number");

                    b.Property<int>("QuranWordId")
                        .HasColumnType("integer")
                        .HasColumnName("quran_word_id");

                    b.Property<short>("SurahNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("surah_number");

                    b.Property<short>("SurahsCount")
                        .HasColumnType("smallint")
                        .HasColumnName("surahs_count");

                    b.Property<string>("TextImlaeiSimple")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text_imlaei_simple");

                    b.Property<string>("TextUthmani")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text_uthmani");

                    b.Property<string>("TextUthmaniSimple")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text_uthmani_simple");

                    b.Property<string>("VerseKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("verse_key");

                    b.Property<short>("WordOrderInAyah")
                        .HasColumnType("smallint")
                        .HasColumnName("word_order_in_ayah");

                    b.Property<short>("WordOrderInSurah")
                        .HasColumnType("smallint")
                        .HasColumnName("word_order_in_surah");

                    b.HasKey("WordOrderInMushaf");

                    b.HasIndex("QuranWordId")
                        .IsUnique();

                    b.HasIndex("SurahNumber", "WordOrderInSurah");

                    b.HasIndex("SurahNumber", "AyahNumber", "WordOrderInAyah");

                    b.ToTable("quran_words_ordered_tashkeel", (string)null);
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.Words.Display.UniqueSimpleWord", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<short>("AyahsCount")
                        .HasColumnType("smallint")
                        .HasColumnName("ayahs_count");

                    b.Property<short>("FirstAyahNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("first_ayah_number");

                    b.Property<short>("FirstLineNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("first_line_number");

                    b.Property<string>("FirstLocation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_location");

                    b.Property<short>("FirstPageNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("first_page_number");

                    b.Property<int>("FirstQuranWordId")
                        .HasColumnType("integer")
                        .HasColumnName("first_quran_word_id");

                    b.Property<short>("FirstSurahNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("first_surah_number");

                    b.Property<int>("FirstWordOrderInMushaf")
                        .HasColumnType("integer")
                        .HasColumnName("first_word_order_in_mushaf");

                    b.Property<int>("OccurrencesCount")
                        .HasColumnType("integer")
                        .HasColumnName("occurrences_count");

                    b.Property<string>("QpcGlyph")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("qpc_glyph");

                    b.Property<short>("SurahsCount")
                        .HasColumnType("smallint")
                        .HasColumnName("surahs_count");

                    b.Property<string>("TextImlaeiSimple")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text_imlaei_simple");

                    b.Property<string>("TextUthmani")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text_uthmani");

                    b.Property<string>("TextUthmaniSimple")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text_uthmani_simple");

                    b.Property<string>("WordKeyImlaeiSimple")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("word_key_imlaei_simple");

                    b.HasKey("Id");

                    b.HasIndex("FirstQuranWordId");

                    b.HasIndex("FirstWordOrderInMushaf")
                        .IsUnique();

                    b.HasIndex("WordKeyImlaeiSimple")
                        .IsUnique();

                    b.ToTable("quran_words_unique_simple", (string)null);
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.Words.Display.UniqueTashkeelWord", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<short>("AyahsCount")
                        .HasColumnType("smallint")
                        .HasColumnName("ayahs_count");

                    b.Property<short>("FirstAyahNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("first_ayah_number");

                    b.Property<short>("FirstLineNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("first_line_number");

                    b.Property<string>("FirstLocation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_location");

                    b.Property<short>("FirstPageNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("first_page_number");

                    b.Property<int>("FirstQuranWordId")
                        .HasColumnType("integer")
                        .HasColumnName("first_quran_word_id");

                    b.Property<short>("FirstSurahNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("first_surah_number");

                    b.Property<int>("FirstWordOrderInMushaf")
                        .HasColumnType("integer")
                        .HasColumnName("first_word_order_in_mushaf");

                    b.Property<int>("OccurrencesCount")
                        .HasColumnType("integer")
                        .HasColumnName("occurrences_count");

                    b.Property<short>("SurahsCount")
                        .HasColumnType("smallint")
                        .HasColumnName("surahs_count");

                    b.Property<string>("TextImlaeiSimple")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text_imlaei_simple");

                    b.Property<string>("TextUthmani")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text_uthmani");

                    b.Property<string>("TextUthmaniSimple")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text_uthmani_simple");

                    b.HasKey("Id");

                    b.HasIndex("FirstQuranWordId");

                    b.HasIndex("FirstWordOrderInMushaf")
                        .IsUnique();

                    b.HasIndex("TextUthmani")
                        .IsUnique();

                    b.ToTable("quran_words_unique_tashkeel", (string)null);
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.Words.Morphology.Irab.QuranI3rabRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DefaultStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("default_status");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("I3rabArabic")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("i3rab_arabic");

                    b.Property<string>("RuleFamily")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rule_family");

                    b.Property<string>("SignatureKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("signature_key");

                    b.Property<short>("SortOrder")
                        .HasColumnType("smallint")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("RuleFamily");

                    b.HasIndex("SignatureKey")
                        .IsUnique();

                    b.ToTable("quran_i3rab_rules", null, t =>
                        {
                            t.HasCheckConstraint("CK_quran_i3rab_rules_default_status", "default_status IN ('approved', 'needs_review', 'unsupported')");
                        });
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.Words.Morphology.PosTag", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("ArabicLabel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("arabic_label");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("EnglishLabel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("english_label");

                    b.Property<short>("SortOrder")
                        .HasColumnType("smallint")
                        .HasColumnName("sort_order");

                    b.HasKey("Code");

                    b.HasIndex("Category");

                    b.HasIndex("SortOrder");

                    b.ToTable("quran_pos_tags", (string)null);
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.Words.Morphology.QuranLemma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FirstWordOrderInMushaf")
                        .HasColumnType("integer")
                        .HasColumnName("first_word_order_in_mushaf");

                    b.Property<string>("LemmaBuckwalter")
                        .HasColumnType("text")
                        .HasColumnName("lemma_buckwalter");

                    b.Property<string>("LemmaText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lemma_text");

                    b.Property<int?>("RootId")
                        .HasColumnType("integer")
                        .HasColumnName("root_id");

                    b.Property<int>("WordsCount")
                        .HasColumnType("integer")
                        .HasColumnName("words_count");

                    b.HasKey("Id");

                    b.HasIndex("FirstWordOrderInMushaf")
                        .IsUnique();

                    b.HasIndex("LemmaText")
                        .IsUnique();

                    b.HasIndex("RootId");

                    b.ToTable("quran_lemmas", (string)null);
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.Words.Morphology.QuranRoot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short>("DistinctLemmasCount")
                        .HasColumnType("smallint")
                        .HasColumnName("distinct_lemmas_count");

                    b.Property<int>("FirstWordOrderInMushaf")
                        .HasColumnType("integer")
                        .HasColumnName("first_word_order_in_mushaf");

                    b.Property<string>("RootBuckwalter")
                        .HasColumnType("text")
                        .HasColumnName("root_buckwalter");

                    b.Property<string>("RootText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("root_text");

                    b.Property<int>("WordsCount")
                        .HasColumnType("integer")
                        .HasColumnName("words_count");

                    b.HasKey("Id");

                    b.HasIndex("FirstWordOrderInMushaf")
                        .IsUnique();

                    b.HasIndex("RootText")
                        .IsUnique();

                    b.HasIndex("WordsCount");

                    b.ToTable("quran_roots", (string)null);
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.Words.Morphology.QuranStem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FirstWordOrderInMushaf")
                        .HasColumnType("integer")
                        .HasColumnName("first_word_order_in_mushaf");

                    b.Property<string>("StemText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stem_text");

                    b.Property<int>("WordsCount")
                        .HasColumnType("integer")
                        .HasColumnName("words_count");

                    b.HasKey("Id");

                    b.HasIndex("FirstWordOrderInMushaf")
                        .IsUnique();

                    b.HasIndex("StemText")
                        .IsUnique();

                    b.ToTable("quran_stems", (string)null);
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.Words.Morphology.WordMorphology", b =>
                {
                    b.Property<int>("QuranWordId")
                        .HasColumnType("integer")
                        .HasColumnName("quran_word_id");

                    b.Property<string>("CaseFeature")
                        .HasColumnType("text")
                        .HasColumnName("case_feature");

                    b.Property<string>("HeadFeaturesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("head_features_json");

                    b.Property<string>("HeadPos")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("head_pos");

                    b.Property<bool>("IsVerb")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verb");

                    b.Property<int?>("LemmaId")
                        .HasColumnType("integer")
                        .HasColumnName("lemma_id");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<int?>("RootId")
                        .HasColumnType("integer")
                        .HasColumnName("root_id");

                    b.Property<short>("SegmentCount")
                        .HasColumnType("smallint")
                        .HasColumnName("segment_count");

                    b.Property<int?>("StemId")
                        .HasColumnType("integer")
                        .HasColumnName("stem_id");

                    b.Property<string>("VerbTense")
                        .HasColumnType("text")
                        .HasColumnName("verb_tense");

                    b.Property<string>("VerbVoice")
                        .HasColumnType("text")
                        .HasColumnName("verb_voice");

                    b.HasKey("QuranWordId");

                    b.HasIndex("CaseFeature");

                    b.HasIndex("HeadPos");

                    b.HasIndex("LemmaId");

                    b.HasIndex("QuranWordId")
                        .IsUnique();

                    b.HasIndex("RootId");

                    b.HasIndex("StemId");

                    b.HasIndex("VerbTense")
                        .HasDatabaseName("IX_quran_word_morphology_verb_tense")
                        .HasFilter("is_verb");

                    b.HasIndex("VerbVoice")
                        .HasDatabaseName("IX_quran_word_morphology_verb_voice")
                        .HasFilter("is_verb");

                    b.ToTable("quran_word_morphology", (string)null);
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.Words.Morphology.WordMorphologySegment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ArabicRenderSource")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("arabic_render_source");

                    b.Property<string>("ArabicRenderTier")
                        .HasColumnType("text")
                        .HasColumnName("arabic_render_tier");

                    b.Property<string>("FeaturesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("features_json");

                    b.Property<string>("FeaturesRaw")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("features_raw");

                    b.Property<string>("FormArabicNormalized")
                        .HasColumnType("text")
                        .HasColumnName("form_arabic_normalized");

                    b.Property<string>("FormBuckwalter")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("form_buckwalter");

                    b.Property<string>("I3rabArabic")
                        .HasColumnType("text")
                        .HasColumnName("i3rab_arabic");

                    b.Property<string>("I3rabReviewReason")
                        .HasColumnType("text")
                        .HasColumnName("i3rab_review_reason");

                    b.Property<int?>("I3rabRuleId")
                        .HasColumnType("integer")
                        .HasColumnName("i3rab_rule_id");

                    b.Property<string>("I3rabStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("unsupported")
                        .HasColumnName("i3rab_status");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("LemmaBuckwalter")
                        .HasColumnType("text")
                        .HasColumnName("lemma_buckwalter");

                    b.Property<string>("Pos")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pos");

                    b.Property<int>("QuranWordId")
                        .HasColumnType("integer")
                        .HasColumnName("quran_word_id");

                    b.Property<string>("RootBuckwalter")
                        .HasColumnType("text")
                        .HasColumnName("root_buckwalter");

                    b.Property<string>("SegmentLocation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("segment_location");

                    b.Property<short>("SegmentNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("segment_number");

                    b.HasKey("Id");

                    b.HasIndex("ArabicRenderTier");

                    b.HasIndex("I3rabRuleId");

                    b.HasIndex("Pos");

                    b.HasIndex("QuranWordId")
                        .HasDatabaseName("IX_quran_word_morphology_segments_stem")
                        .HasFilter("kind = 'STEM'");

                    b.HasIndex("QuranWordId", "SegmentNumber")
                        .IsUnique();

                    b.ToTable("quran_word_morphology_segments", null, t =>
                        {
                            t.HasCheckConstraint("CK_quran_word_morphology_segments_i3rab_status", "i3rab_status IN ('approved', 'needs_review', 'unsupported')");
                        });
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.Words.QuranWord", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int>("AyahId")
                        .HasColumnType("integer")
                        .HasColumnName("ayah_id");

                    b.Property<short>("AyahNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("ayah_number");

                    b.Property<bool>("IsAyahMarker")
                        .HasColumnType("boolean")
                        .HasColumnName("is_ayah_marker");

                    b.Property<short>("LineNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("line_number");

                    b.Property<short>("LineWordOrder")
                        .HasColumnType("smallint")
                        .HasColumnName("line_word_order");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<short>("PageNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("page_number");

                    b.Property<string>("QpcGlyph")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("qpc_glyph");

                    b.Property<short>("SurahNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("surah_number");

                    b.Property<string>("TextImlaeiSimple")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text_imlaei_simple");

                    b.Property<string>("TextUthmani")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text_uthmani");

                    b.Property<string>("TextUthmaniSimple")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text_uthmani_simple");

                    b.Property<int?>("UniqueSimpleWordId")
                        .HasColumnType("integer")
                        .HasColumnName("unique_simple_word_id");

                    b.Property<int?>("UniqueTashkeelWordId")
                        .HasColumnType("integer")
                        .HasColumnName("unique_tashkeel_word_id");

                    b.Property<string>("WordKeyImlaeiSimple")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("word_key_imlaei_simple");

                    b.Property<short>("WordNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("word_number");

                    b.HasKey("Id");

                    b.HasIndex("AyahId");

                    b.HasIndex("Location")
                        .IsUnique();

                    b.HasIndex("UniqueSimpleWordId")
                        .HasDatabaseName("IX_quran_words_unique_simple_word_id")
                        .HasFilter("is_ayah_marker = false AND unique_simple_word_id IS NOT NULL");

                    b.HasIndex("UniqueTashkeelWordId")
                        .HasDatabaseName("IX_quran_words_unique_tashkeel_word_id")
                        .HasFilter("is_ayah_marker = false AND unique_tashkeel_word_id IS NOT NULL");

                    b.HasIndex("PageNumber", "LineNumber", "LineWordOrder");

                    b.HasIndex(new[] { "SurahNumber", "AyahNumber", "WordNumber" }, "IX_quran_words_readable_surah_ayah_word")
                        .HasDatabaseName("IX_quran_words_readable_surah_ayah_word")
                        .HasFilter("is_ayah_marker = false");

                    b.HasIndex(new[] { "SurahNumber", "AyahNumber", "WordNumber" }, "IX_quran_words_surah_ayah_word")
                        .HasDatabaseName("IX_quran_words_surah_ayah_word");

                    b.HasIndex(new[] { "WordKeyImlaeiSimple" }, "IX_quran_words_word_key_imlaei_simple")
                        .HasDatabaseName("IX_quran_words_word_key_imlaei_simple")
                        .HasFilter("is_ayah_marker = false");

                    b.ToTable("quran_words", (string)null);
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.Ayahs.Ayah", b =>
                {
                    b.HasOne("QuranDashboard.Domain.Quran.Navigation.Hizb", null)
                        .WithMany()
                        .HasForeignKey("HizbNumber")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QuranDashboard.Domain.Quran.Navigation.Juz", null)
                        .WithMany()
                        .HasForeignKey("JuzNumber")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QuranDashboard.Domain.Quran.Navigation.Rub", null)
                        .WithMany()
                        .HasForeignKey("RubNumber")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QuranDashboard.Domain.Quran.Surahs.Surah", "Surah")
                        .WithMany()
                        .HasForeignKey("SurahNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Surah");
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.FullI3rab.FullI3rabAyahEntry", b =>
                {
                    b.HasOne("QuranDashboard.Domain.Quran.Ayahs.Ayah", null)
                        .WithMany()
                        .HasForeignKey("AyahId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuranDashboard.Domain.Quran.FullI3rab.FullI3rabEntry", null)
                        .WithMany()
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuranDashboard.Domain.Quran.FullI3rab.FullI3rabSource", null)
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.FullI3rab.FullI3rabEntry", b =>
                {
                    b.HasOne("QuranDashboard.Domain.Quran.Ayahs.Ayah", null)
                        .WithMany()
                        .HasForeignKey("LeaderAyahId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuranDashboard.Domain.Quran.FullI3rab.FullI3rabSource", null)
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.MushafPages.MushafLine", b =>
                {
                    b.HasOne("QuranDashboard.Domain.Quran.Words.QuranWord", "FirstWord")
                        .WithMany()
                        .HasForeignKey("FirstWordId");

                    b.HasOne("QuranDashboard.Domain.Quran.Words.QuranWord", "LastWord")
                        .WithMany()
                        .HasForeignKey("LastWordId");

                    b.HasOne("QuranDashboard.Domain.Quran.MushafPages.MushafPage", "Page")
                        .WithMany()
                        .HasForeignKey("PageNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuranDashboard.Domain.Quran.Surahs.Surah", "Surah")
                        .WithMany()
                        .HasForeignKey("SurahNumber");

                    b.Navigation("FirstWord");

                    b.Navigation("LastWord");

                    b.Navigation("Page");

                    b.Navigation("Surah");
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.Mutashabihat.MutashabihatGroup", b =>
                {
                    b.HasOne("QuranDashboard.Domain.Quran.Ayahs.Ayah", null)
                        .WithMany()
                        .HasForeignKey("RepresentativeAyahId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.Mutashabihat.MutashabihatOccurrence", b =>
                {
                    b.HasOne("QuranDashboard.Domain.Quran.Ayahs.Ayah", null)
                        .WithMany()
                        .HasForeignKey("AyahId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuranDashboard.Domain.Quran.Mutashabihat.MutashabihatGroup", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.Mutashabihat.SimilarAyahLink", b =>
                {
                    b.HasOne("QuranDashboard.Domain.Quran.Ayahs.Ayah", null)
                        .WithMany()
                        .HasForeignKey("SourceAyahId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuranDashboard.Domain.Quran.Ayahs.Ayah", null)
                        .WithMany()
                        .HasForeignKey("TargetAyahId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.Navigation.Hizb", b =>
                {
                    b.HasOne("QuranDashboard.Domain.Quran.Ayahs.Ayah", null)
                        .WithMany()
                        .HasForeignKey("FirstAyahId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuranDashboard.Domain.Quran.Navigation.Juz", null)
                        .WithMany()
                        .HasForeignKey("JuzNumber")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuranDashboard.Domain.Quran.Ayahs.Ayah", null)
                        .WithMany()
                        .HasForeignKey("LastAyahId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.Navigation.Juz", b =>
                {
                    b.HasOne("QuranDashboard.Domain.Quran.Ayahs.Ayah", null)
                        .WithMany()
                        .HasForeignKey("FirstAyahId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuranDashboard.Domain.Quran.Ayahs.Ayah", null)
                        .WithMany()
                        .HasForeignKey("LastAyahId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.Navigation.Rub", b =>
                {
                    b.HasOne("QuranDashboard.Domain.Quran.Ayahs.Ayah", null)
                        .WithMany()
                        .HasForeignKey("FirstAyahId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuranDashboard.Domain.Quran.Navigation.Hizb", null)
                        .WithMany()
                        .HasForeignKey("HizbNumber")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuranDashboard.Domain.Quran.Ayahs.Ayah", null)
                        .WithMany()
                        .HasForeignKey("LastAyahId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.Navigation.Sajda", b =>
                {
                    b.HasOne("QuranDashboard.Domain.Quran.Ayahs.Ayah", null)
                        .WithMany()
                        .HasForeignKey("AyahId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.Tafsirs.TafsirAyahEntry", b =>
                {
                    b.HasOne("QuranDashboard.Domain.Quran.Ayahs.Ayah", null)
                        .WithMany()
                        .HasForeignKey("AyahId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuranDashboard.Domain.Quran.Tafsirs.TafsirSource", null)
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuranDashboard.Domain.Quran.Tafsirs.TafsirEntry", null)
                        .WithMany()
                        .HasForeignKey("TafsirEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.Tafsirs.TafsirEntry", b =>
                {
                    b.HasOne("QuranDashboard.Domain.Quran.Ayahs.Ayah", null)
                        .WithMany()
                        .HasForeignKey("LeaderAyahId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuranDashboard.Domain.Quran.Tafsirs.TafsirSource", null)
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.Translations.TranslationAyahEntry", b =>
                {
                    b.HasOne("QuranDashboard.Domain.Quran.Ayahs.Ayah", null)
                        .WithMany()
                        .HasForeignKey("AyahId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuranDashboard.Domain.Quran.Translations.TranslationSource", null)
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.Words.Display.OrderedSimpleWord", b =>
                {
                    b.HasOne("QuranDashboard.Domain.Quran.Words.QuranWord", null)
                        .WithMany()
                        .HasForeignKey("QuranWordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.Words.Display.OrderedTashkeelWord", b =>
                {
                    b.HasOne("QuranDashboard.Domain.Quran.Words.QuranWord", null)
                        .WithMany()
                        .HasForeignKey("QuranWordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.Words.Display.UniqueSimpleWord", b =>
                {
                    b.HasOne("QuranDashboard.Domain.Quran.Words.QuranWord", null)
                        .WithMany()
                        .HasForeignKey("FirstQuranWordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.Words.Display.UniqueTashkeelWord", b =>
                {
                    b.HasOne("QuranDashboard.Domain.Quran.Words.QuranWord", null)
                        .WithMany()
                        .HasForeignKey("FirstQuranWordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.Words.Morphology.QuranLemma", b =>
                {
                    b.HasOne("QuranDashboard.Domain.Quran.Words.Morphology.QuranRoot", "Root")
                        .WithMany()
                        .HasForeignKey("RootId");

                    b.Navigation("Root");
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.Words.Morphology.WordMorphology", b =>
                {
                    b.HasOne("QuranDashboard.Domain.Quran.Words.Morphology.PosTag", null)
                        .WithMany()
                        .HasForeignKey("HeadPos")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuranDashboard.Domain.Quran.Words.Morphology.QuranLemma", "Lemma")
                        .WithMany()
                        .HasForeignKey("LemmaId");

                    b.HasOne("QuranDashboard.Domain.Quran.Words.QuranWord", "QuranWord")
                        .WithMany()
                        .HasForeignKey("QuranWordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuranDashboard.Domain.Quran.Words.Morphology.QuranRoot", "Root")
                        .WithMany()
                        .HasForeignKey("RootId");

                    b.HasOne("QuranDashboard.Domain.Quran.Words.Morphology.QuranStem", "Stem")
                        .WithMany()
                        .HasForeignKey("StemId");

                    b.Navigation("Lemma");

                    b.Navigation("QuranWord");

                    b.Navigation("Root");

                    b.Navigation("Stem");
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.Words.Morphology.WordMorphologySegment", b =>
                {
                    b.HasOne("QuranDashboard.Domain.Quran.Words.Morphology.Irab.QuranI3rabRule", "I3rabRule")
                        .WithMany()
                        .HasForeignKey("I3rabRuleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QuranDashboard.Domain.Quran.Words.Morphology.PosTag", null)
                        .WithMany()
                        .HasForeignKey("Pos")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuranDashboard.Domain.Quran.Words.QuranWord", "QuranWord")
                        .WithMany()
                        .HasForeignKey("QuranWordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("I3rabRule");

                    b.Navigation("QuranWord");
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.Words.QuranWord", b =>
                {
                    b.HasOne("QuranDashboard.Domain.Quran.Ayahs.Ayah", "Ayah")
                        .WithMany()
                        .HasForeignKey("AyahId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuranDashboard.Domain.Quran.MushafPages.MushafPage", "Page")
                        .WithMany()
                        .HasForeignKey("PageNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ayah");

                    b.Navigation("Page");
                });
#pragma warning restore 612, 618
        }
    }
}
