// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QuranDashboard.Infrastructure.Persistence;

#nullable disable

namespace QuranDashboard.Infrastructure.Migrations
{
    [DbContext(typeof(QuranDashboardDbContext))]
    partial class QuranDashboardDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QuranDashboard.Domain.Quran.Ayahs.Ayah", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<short>("AyahNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("ayah_number");

                    b.Property<short>("PageFrom")
                        .HasColumnType("smallint")
                        .HasColumnName("page_from");

                    b.Property<short>("PageTo")
                        .HasColumnType("smallint")
                        .HasColumnName("page_to");

                    b.Property<short>("SurahNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("surah_number");

                    b.Property<string>("TextUthmani")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text_uthmani");

                    b.Property<string>("VerseKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("verse_key");

                    b.Property<short>("WordsCountReal")
                        .HasColumnType("smallint")
                        .HasColumnName("words_count_real");

                    b.Property<short>("WordsCountSource")
                        .HasColumnType("smallint")
                        .HasColumnName("words_count_source");

                    b.HasKey("Id");

                    b.HasIndex("VerseKey")
                        .IsUnique();

                    b.HasIndex("SurahNumber", "AyahNumber")
                        .IsUnique();

                    b.ToTable("quran_ayahs", (string)null);
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.MushafPages.MushafLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("FirstWordId")
                        .HasColumnType("integer")
                        .HasColumnName("first_word_id");

                    b.Property<bool>("IsCentered")
                        .HasColumnType("boolean")
                        .HasColumnName("is_centered");

                    b.Property<int?>("LastWordId")
                        .HasColumnType("integer")
                        .HasColumnName("last_word_id");

                    b.Property<short>("LineNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("line_number");

                    b.Property<string>("LineType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("line_type");

                    b.Property<short>("PageNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("page_number");

                    b.Property<short?>("SurahNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("surah_number");

                    b.Property<short>("WordsCount")
                        .HasColumnType("smallint")
                        .HasColumnName("words_count");

                    b.HasKey("Id");

                    b.HasIndex("FirstWordId");

                    b.HasIndex("LastWordId");

                    b.HasIndex("SurahNumber");

                    b.HasIndex("PageNumber", "LineNumber")
                        .IsUnique();

                    b.ToTable("quran_mushaf_lines", (string)null);
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.MushafPages.MushafPage", b =>
                {
                    b.Property<short>("PageNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("page_number");

                    b.Property<short>("FirstAyahNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("first_ayah_number");

                    b.Property<short>("FirstSurahNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("first_surah_number");

                    b.Property<short>("LastAyahNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("last_ayah_number");

                    b.Property<short>("LastSurahNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("last_surah_number");

                    b.Property<short>("LinesCount")
                        .HasColumnType("smallint")
                        .HasColumnName("lines_count");

                    b.HasKey("PageNumber");

                    b.ToTable("quran_mushaf_pages", (string)null);
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.Mutashabihat.MutashabihatGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short>("DistinctAyahCount")
                        .HasColumnType("smallint")
                        .HasColumnName("distinct_ayah_count");

                    b.Property<short>("DistinctSurahCount")
                        .HasColumnType("smallint")
                        .HasColumnName("distinct_surah_count");

                    b.Property<short>("OccurrenceCount")
                        .HasColumnType("smallint")
                        .HasColumnName("occurrence_count");

                    b.Property<string>("RawSourceCounts")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_source_counts");

                    b.Property<int>("RepresentativeAyahId")
                        .HasColumnType("integer")
                        .HasColumnName("representative_ayah_id");

                    b.Property<short>("RepresentativeWordFrom")
                        .HasColumnType("smallint")
                        .HasColumnName("representative_word_from");

                    b.Property<short>("RepresentativeWordTo")
                        .HasColumnType("smallint")
                        .HasColumnName("representative_word_to");

                    b.Property<int>("SourceGroupId")
                        .HasColumnType("integer")
                        .HasColumnName("source_group_id");

                    b.HasKey("Id");

                    b.HasIndex("RepresentativeAyahId");

                    b.HasIndex("SourceGroupId")
                        .IsUnique();

                    b.ToTable("quran_mutashabihat_groups", (string)null);
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.Mutashabihat.MutashabihatOccurrence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AyahId")
                        .HasColumnType("integer")
                        .HasColumnName("ayah_id");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<bool>("IsRepresentative")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_representative");

                    b.Property<short>("WordFrom")
                        .HasColumnType("smallint")
                        .HasColumnName("word_from");

                    b.Property<short>("WordTo")
                        .HasColumnType("smallint")
                        .HasColumnName("word_to");

                    b.HasKey("Id");

                    b.HasIndex("AyahId");

                    b.HasIndex("GroupId", "AyahId", "WordFrom", "WordTo")
                        .IsUnique();

                    b.ToTable("quran_mutashabihat_occurrences", (string)null);
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.Mutashabihat.SimilarAyahLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short>("Coverage")
                        .HasColumnType("smallint")
                        .HasColumnName("coverage");

                    b.Property<string>("MatchWords")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("match_words");

                    b.Property<short>("MatchedWordsCount")
                        .HasColumnType("smallint")
                        .HasColumnName("matched_words_count");

                    b.Property<short>("Score")
                        .HasColumnType("smallint")
                        .HasColumnName("score");

                    b.Property<int>("SourceAyahId")
                        .HasColumnType("integer")
                        .HasColumnName("source_ayah_id");

                    b.Property<int>("TargetAyahId")
                        .HasColumnType("integer")
                        .HasColumnName("target_ayah_id");

                    b.HasKey("Id");

                    b.HasIndex("TargetAyahId");

                    b.HasIndex("SourceAyahId", "TargetAyahId")
                        .IsUnique();

                    b.ToTable("quran_similar_ayah_links", null, t =>
                        {
                            t.HasCheckConstraint("CK_quran_similar_ayah_links_no_self", "source_ayah_id <> target_ayah_id");
                        });
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.Surahs.Surah", b =>
                {
                    b.Property<short>("SurahNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("surah_number");

                    b.Property<bool>("BismillahPre")
                        .HasColumnType("boolean")
                        .HasColumnName("bismillah_pre");

                    b.Property<string>("NameArabic")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_arabic");

                    b.Property<string>("NameSimple")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_simple");

                    b.Property<string>("NameTransliteration")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_transliteration");

                    b.Property<short>("RevelationOrder")
                        .HasColumnType("smallint")
                        .HasColumnName("revelation_order");

                    b.Property<string>("RevelationPlace")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("revelation_place");

                    b.Property<short>("VersesCount")
                        .HasColumnType("smallint")
                        .HasColumnName("verses_count");

                    b.HasKey("SurahNumber");

                    b.HasIndex("NameArabic")
                        .IsUnique();

                    b.ToTable("quran_surahs", (string)null);
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.Words.Display.OrderedSimpleWord", b =>
                {
                    b.Property<int>("WordOrderInMushaf")
                        .HasColumnType("integer")
                        .HasColumnName("word_order_in_mushaf");

                    b.Property<short>("AyahNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("ayah_number");

                    b.Property<short>("AyahsCount")
                        .HasColumnType("smallint")
                        .HasColumnName("ayahs_count");

                    b.Property<short>("LineNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("line_number");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<int>("OccurrencesCount")
                        .HasColumnType("integer")
                        .HasColumnName("occurrences_count");

                    b.Property<short>("PageNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("page_number");

                    b.Property<int>("QuranWordId")
                        .HasColumnType("integer")
                        .HasColumnName("quran_word_id");

                    b.Property<short>("SurahNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("surah_number");

                    b.Property<short>("SurahsCount")
                        .HasColumnType("smallint")
                        .HasColumnName("surahs_count");

                    b.Property<string>("TextImlaeiSimple")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text_imlaei_simple");

                    b.Property<string>("TextUthmaniSimple")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text_uthmani_simple");

                    b.Property<string>("VerseKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("verse_key");

                    b.Property<string>("WordKeyImlaeiSimple")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("word_key_imlaei_simple");

                    b.Property<short>("WordOrderInAyah")
                        .HasColumnType("smallint")
                        .HasColumnName("word_order_in_ayah");

                    b.Property<short>("WordOrderInSurah")
                        .HasColumnType("smallint")
                        .HasColumnName("word_order_in_surah");

                    b.HasKey("WordOrderInMushaf");

                    b.HasIndex("QuranWordId")
                        .IsUnique();

                    b.HasIndex("SurahNumber", "WordOrderInSurah");

                    b.HasIndex("SurahNumber", "AyahNumber", "WordOrderInAyah");

                    b.ToTable("quran_words_ordered_simple", (string)null);
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.Words.Display.OrderedTashkeelWord", b =>
                {
                    b.Property<int>("WordOrderInMushaf")
                        .HasColumnType("integer")
                        .HasColumnName("word_order_in_mushaf");

                    b.Property<short>("AyahNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("ayah_number");

                    b.Property<short>("AyahsCount")
                        .HasColumnType("smallint")
                        .HasColumnName("ayahs_count");

                    b.Property<short>("LineNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("line_number");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<int>("OccurrencesCount")
                        .HasColumnType("integer")
                        .HasColumnName("occurrences_count");

                    b.Property<short>("PageNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("page_number");

                    b.Property<int>("QuranWordId")
                        .HasColumnType("integer")
                        .HasColumnName("quran_word_id");

                    b.Property<short>("SurahNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("surah_number");

                    b.Property<short>("SurahsCount")
                        .HasColumnType("smallint")
                        .HasColumnName("surahs_count");

                    b.Property<string>("TextImlaeiSimple")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text_imlaei_simple");

                    b.Property<string>("TextUthmani")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text_uthmani");

                    b.Property<string>("TextUthmaniSimple")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text_uthmani_simple");

                    b.Property<string>("VerseKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("verse_key");

                    b.Property<short>("WordOrderInAyah")
                        .HasColumnType("smallint")
                        .HasColumnName("word_order_in_ayah");

                    b.Property<short>("WordOrderInSurah")
                        .HasColumnType("smallint")
                        .HasColumnName("word_order_in_surah");

                    b.HasKey("WordOrderInMushaf");

                    b.HasIndex("QuranWordId")
                        .IsUnique();

                    b.HasIndex("SurahNumber", "WordOrderInSurah");

                    b.HasIndex("SurahNumber", "AyahNumber", "WordOrderInAyah");

                    b.ToTable("quran_words_ordered_tashkeel", (string)null);
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.Words.Display.UniqueSimpleWord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short>("AyahsCount")
                        .HasColumnType("smallint")
                        .HasColumnName("ayahs_count");

                    b.Property<short>("FirstAyahNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("first_ayah_number");

                    b.Property<short>("FirstLineNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("first_line_number");

                    b.Property<string>("FirstLocation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_location");

                    b.Property<short>("FirstPageNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("first_page_number");

                    b.Property<int>("FirstQuranWordId")
                        .HasColumnType("integer")
                        .HasColumnName("first_quran_word_id");

                    b.Property<short>("FirstSurahNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("first_surah_number");

                    b.Property<int>("FirstWordOrderInMushaf")
                        .HasColumnType("integer")
                        .HasColumnName("first_word_order_in_mushaf");

                    b.Property<int>("OccurrencesCount")
                        .HasColumnType("integer")
                        .HasColumnName("occurrences_count");

                    b.Property<string>("QpcGlyph")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("qpc_glyph");

                    b.Property<short>("SurahsCount")
                        .HasColumnType("smallint")
                        .HasColumnName("surahs_count");

                    b.Property<string>("TextImlaeiSimple")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text_imlaei_simple");

                    b.Property<string>("TextUthmani")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text_uthmani");

                    b.Property<string>("TextUthmaniSimple")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text_uthmani_simple");

                    b.Property<string>("WordKeyImlaeiSimple")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("word_key_imlaei_simple");

                    b.HasKey("Id");

                    b.HasIndex("FirstQuranWordId");

                    b.HasIndex("FirstWordOrderInMushaf")
                        .IsUnique();

                    b.HasIndex("WordKeyImlaeiSimple")
                        .IsUnique();

                    b.ToTable("quran_words_unique_simple", (string)null);
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.Words.Display.UniqueTashkeelWord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short>("AyahsCount")
                        .HasColumnType("smallint")
                        .HasColumnName("ayahs_count");

                    b.Property<short>("FirstAyahNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("first_ayah_number");

                    b.Property<short>("FirstLineNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("first_line_number");

                    b.Property<string>("FirstLocation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_location");

                    b.Property<short>("FirstPageNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("first_page_number");

                    b.Property<int>("FirstQuranWordId")
                        .HasColumnType("integer")
                        .HasColumnName("first_quran_word_id");

                    b.Property<short>("FirstSurahNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("first_surah_number");

                    b.Property<int>("FirstWordOrderInMushaf")
                        .HasColumnType("integer")
                        .HasColumnName("first_word_order_in_mushaf");

                    b.Property<int>("OccurrencesCount")
                        .HasColumnType("integer")
                        .HasColumnName("occurrences_count");

                    b.Property<short>("SurahsCount")
                        .HasColumnType("smallint")
                        .HasColumnName("surahs_count");

                    b.Property<string>("TextImlaeiSimple")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text_imlaei_simple");

                    b.Property<string>("TextUthmani")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text_uthmani");

                    b.Property<string>("TextUthmaniSimple")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text_uthmani_simple");

                    b.HasKey("Id");

                    b.HasIndex("FirstQuranWordId");

                    b.HasIndex("FirstWordOrderInMushaf")
                        .IsUnique();

                    b.HasIndex("TextUthmani")
                        .IsUnique();

                    b.ToTable("quran_words_unique_tashkeel", (string)null);
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.Words.Morphology.Irab.QuranI3rabRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DefaultStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("default_status");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("I3rabArabic")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("i3rab_arabic");

                    b.Property<string>("RuleFamily")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rule_family");

                    b.Property<string>("SignatureKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("signature_key");

                    b.Property<short>("SortOrder")
                        .HasColumnType("smallint")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("RuleFamily");

                    b.HasIndex("SignatureKey")
                        .IsUnique();

                    b.ToTable("quran_i3rab_rules", null, t =>
                        {
                            t.HasCheckConstraint("CK_quran_i3rab_rules_default_status", "default_status IN ('approved', 'needs_review', 'unsupported')");
                        });
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.Words.Morphology.PosTag", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("ArabicLabel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("arabic_label");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("EnglishLabel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("english_label");

                    b.Property<short>("SortOrder")
                        .HasColumnType("smallint")
                        .HasColumnName("sort_order");

                    b.HasKey("Code");

                    b.HasIndex("Category");

                    b.HasIndex("SortOrder");

                    b.ToTable("quran_pos_tags", (string)null);
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.Words.Morphology.QuranLemma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FirstWordOrderInMushaf")
                        .HasColumnType("integer")
                        .HasColumnName("first_word_order_in_mushaf");

                    b.Property<string>("LemmaBuckwalter")
                        .HasColumnType("text")
                        .HasColumnName("lemma_buckwalter");

                    b.Property<string>("LemmaText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lemma_text");

                    b.Property<int?>("RootId")
                        .HasColumnType("integer")
                        .HasColumnName("root_id");

                    b.Property<int>("WordsCount")
                        .HasColumnType("integer")
                        .HasColumnName("words_count");

                    b.HasKey("Id");

                    b.HasIndex("FirstWordOrderInMushaf")
                        .IsUnique();

                    b.HasIndex("LemmaText")
                        .IsUnique();

                    b.HasIndex("RootId");

                    b.ToTable("quran_lemmas", (string)null);
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.Words.Morphology.QuranRoot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short>("DistinctLemmasCount")
                        .HasColumnType("smallint")
                        .HasColumnName("distinct_lemmas_count");

                    b.Property<int>("FirstWordOrderInMushaf")
                        .HasColumnType("integer")
                        .HasColumnName("first_word_order_in_mushaf");

                    b.Property<string>("RootBuckwalter")
                        .HasColumnType("text")
                        .HasColumnName("root_buckwalter");

                    b.Property<string>("RootText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("root_text");

                    b.Property<int>("WordsCount")
                        .HasColumnType("integer")
                        .HasColumnName("words_count");

                    b.HasKey("Id");

                    b.HasIndex("FirstWordOrderInMushaf")
                        .IsUnique();

                    b.HasIndex("RootText")
                        .IsUnique();

                    b.HasIndex("WordsCount");

                    b.ToTable("quran_roots", (string)null);
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.Words.Morphology.QuranStem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FirstWordOrderInMushaf")
                        .HasColumnType("integer")
                        .HasColumnName("first_word_order_in_mushaf");

                    b.Property<string>("StemText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stem_text");

                    b.Property<int>("WordsCount")
                        .HasColumnType("integer")
                        .HasColumnName("words_count");

                    b.HasKey("Id");

                    b.HasIndex("FirstWordOrderInMushaf")
                        .IsUnique();

                    b.HasIndex("StemText")
                        .IsUnique();

                    b.ToTable("quran_stems", (string)null);
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.Words.Morphology.WordMorphology", b =>
                {
                    b.Property<int>("QuranWordId")
                        .HasColumnType("integer")
                        .HasColumnName("quran_word_id");

                    b.Property<string>("CaseFeature")
                        .HasColumnType("text")
                        .HasColumnName("case_feature");

                    b.Property<string>("HeadFeaturesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("head_features_json");

                    b.Property<string>("HeadPos")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("head_pos");

                    b.Property<bool>("IsVerb")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verb");

                    b.Property<int?>("LemmaId")
                        .HasColumnType("integer")
                        .HasColumnName("lemma_id");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<int?>("RootId")
                        .HasColumnType("integer")
                        .HasColumnName("root_id");

                    b.Property<short>("SegmentCount")
                        .HasColumnType("smallint")
                        .HasColumnName("segment_count");

                    b.Property<int?>("StemId")
                        .HasColumnType("integer")
                        .HasColumnName("stem_id");

                    b.Property<string>("VerbTense")
                        .HasColumnType("text")
                        .HasColumnName("verb_tense");

                    b.Property<string>("VerbVoice")
                        .HasColumnType("text")
                        .HasColumnName("verb_voice");

                    b.HasKey("QuranWordId");

                    b.HasIndex("CaseFeature");

                    b.HasIndex("HeadPos");

                    b.HasIndex("LemmaId");

                    b.HasIndex("QuranWordId")
                        .IsUnique();

                    b.HasIndex("RootId");

                    b.HasIndex("StemId");

                    b.HasIndex("VerbTense")
                        .HasDatabaseName("IX_quran_word_morphology_verb_tense")
                        .HasFilter("is_verb");

                    b.HasIndex("VerbVoice")
                        .HasDatabaseName("IX_quran_word_morphology_verb_voice")
                        .HasFilter("is_verb");

                    b.ToTable("quran_word_morphology", (string)null);
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.Words.Morphology.WordMorphologySegment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ArabicRenderSource")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("arabic_render_source");

                    b.Property<string>("ArabicRenderTier")
                        .HasColumnType("text")
                        .HasColumnName("arabic_render_tier");

                    b.Property<string>("FeaturesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("features_json");

                    b.Property<string>("FeaturesRaw")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("features_raw");

                    b.Property<string>("FormArabicNormalized")
                        .HasColumnType("text")
                        .HasColumnName("form_arabic_normalized");

                    b.Property<string>("FormBuckwalter")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("form_buckwalter");

                    b.Property<string>("I3rabArabic")
                        .HasColumnType("text")
                        .HasColumnName("i3rab_arabic");

                    b.Property<string>("I3rabReviewReason")
                        .HasColumnType("text")
                        .HasColumnName("i3rab_review_reason");

                    b.Property<int?>("I3rabRuleId")
                        .HasColumnType("integer")
                        .HasColumnName("i3rab_rule_id");

                    b.Property<string>("I3rabStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("unsupported")
                        .HasColumnName("i3rab_status");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("LemmaBuckwalter")
                        .HasColumnType("text")
                        .HasColumnName("lemma_buckwalter");

                    b.Property<string>("Pos")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pos");

                    b.Property<int>("QuranWordId")
                        .HasColumnType("integer")
                        .HasColumnName("quran_word_id");

                    b.Property<string>("RootBuckwalter")
                        .HasColumnType("text")
                        .HasColumnName("root_buckwalter");

                    b.Property<string>("SegmentLocation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("segment_location");

                    b.Property<short>("SegmentNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("segment_number");

                    b.HasKey("Id");

                    b.HasIndex("ArabicRenderTier");

                    b.HasIndex("I3rabRuleId");

                    b.HasIndex("Pos");

                    b.HasIndex("QuranWordId")
                        .HasDatabaseName("IX_quran_word_morphology_segments_stem")
                        .HasFilter("kind = 'STEM'");

                    b.HasIndex("QuranWordId", "SegmentNumber")
                        .IsUnique();

                    b.ToTable("quran_word_morphology_segments", null, t =>
                        {
                            t.HasCheckConstraint("CK_quran_word_morphology_segments_i3rab_status", "i3rab_status IN ('approved', 'needs_review', 'unsupported')");
                        });
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.Words.QuranWord", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int>("AyahId")
                        .HasColumnType("integer")
                        .HasColumnName("ayah_id");

                    b.Property<short>("AyahNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("ayah_number");

                    b.Property<bool>("IsAyahMarker")
                        .HasColumnType("boolean")
                        .HasColumnName("is_ayah_marker");

                    b.Property<short>("LineNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("line_number");

                    b.Property<short>("LineWordOrder")
                        .HasColumnType("smallint")
                        .HasColumnName("line_word_order");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<short>("PageNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("page_number");

                    b.Property<string>("QpcGlyph")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("qpc_glyph");

                    b.Property<short>("SurahNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("surah_number");

                    b.Property<string>("TextImlaeiSimple")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text_imlaei_simple");

                    b.Property<string>("TextUthmani")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text_uthmani");

                    b.Property<string>("TextUthmaniSimple")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text_uthmani_simple");

                    b.Property<int?>("UniqueSimpleWordId")
                        .HasColumnType("integer")
                        .HasColumnName("unique_simple_word_id");

                    b.Property<int?>("UniqueTashkeelWordId")
                        .HasColumnType("integer")
                        .HasColumnName("unique_tashkeel_word_id");

                    b.Property<string>("WordKeyImlaeiSimple")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("word_key_imlaei_simple");

                    b.Property<short>("WordNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("word_number");

                    b.HasKey("Id");

                    b.HasIndex("AyahId");

                    b.HasIndex("Location")
                        .IsUnique();

                    b.HasIndex("UniqueSimpleWordId")
                        .HasDatabaseName("IX_quran_words_unique_simple_word_id")
                        .HasFilter("is_ayah_marker = false AND unique_simple_word_id IS NOT NULL");

                    b.HasIndex("UniqueTashkeelWordId")
                        .HasDatabaseName("IX_quran_words_unique_tashkeel_word_id")
                        .HasFilter("is_ayah_marker = false AND unique_tashkeel_word_id IS NOT NULL");

                    b.HasIndex("PageNumber", "LineNumber", "LineWordOrder");

                    b.HasIndex(new[] { "SurahNumber", "AyahNumber", "WordNumber" }, "IX_quran_words_readable_surah_ayah_word")
                        .HasDatabaseName("IX_quran_words_readable_surah_ayah_word")
                        .HasFilter("is_ayah_marker = false");

                    b.HasIndex(new[] { "SurahNumber", "AyahNumber", "WordNumber" }, "IX_quran_words_surah_ayah_word")
                        .HasDatabaseName("IX_quran_words_surah_ayah_word");

                    b.HasIndex(new[] { "WordKeyImlaeiSimple" }, "IX_quran_words_word_key_imlaei_simple")
                        .HasDatabaseName("IX_quran_words_word_key_imlaei_simple")
                        .HasFilter("is_ayah_marker = false");

                    b.ToTable("quran_words", (string)null);
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.Ayahs.Ayah", b =>
                {
                    b.HasOne("QuranDashboard.Domain.Quran.Surahs.Surah", "Surah")
                        .WithMany()
                        .HasForeignKey("SurahNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Surah");
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.MushafPages.MushafLine", b =>
                {
                    b.HasOne("QuranDashboard.Domain.Quran.Words.QuranWord", "FirstWord")
                        .WithMany()
                        .HasForeignKey("FirstWordId");

                    b.HasOne("QuranDashboard.Domain.Quran.Words.QuranWord", "LastWord")
                        .WithMany()
                        .HasForeignKey("LastWordId");

                    b.HasOne("QuranDashboard.Domain.Quran.MushafPages.MushafPage", "Page")
                        .WithMany()
                        .HasForeignKey("PageNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuranDashboard.Domain.Quran.Surahs.Surah", "Surah")
                        .WithMany()
                        .HasForeignKey("SurahNumber");

                    b.Navigation("FirstWord");

                    b.Navigation("LastWord");

                    b.Navigation("Page");

                    b.Navigation("Surah");
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.Mutashabihat.MutashabihatGroup", b =>
                {
                    b.HasOne("QuranDashboard.Domain.Quran.Ayahs.Ayah", null)
                        .WithMany()
                        .HasForeignKey("RepresentativeAyahId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.Mutashabihat.MutashabihatOccurrence", b =>
                {
                    b.HasOne("QuranDashboard.Domain.Quran.Ayahs.Ayah", null)
                        .WithMany()
                        .HasForeignKey("AyahId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuranDashboard.Domain.Quran.Mutashabihat.MutashabihatGroup", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.Mutashabihat.SimilarAyahLink", b =>
                {
                    b.HasOne("QuranDashboard.Domain.Quran.Ayahs.Ayah", null)
                        .WithMany()
                        .HasForeignKey("SourceAyahId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuranDashboard.Domain.Quran.Ayahs.Ayah", null)
                        .WithMany()
                        .HasForeignKey("TargetAyahId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.Words.Display.OrderedSimpleWord", b =>
                {
                    b.HasOne("QuranDashboard.Domain.Quran.Words.QuranWord", null)
                        .WithMany()
                        .HasForeignKey("QuranWordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.Words.Display.OrderedTashkeelWord", b =>
                {
                    b.HasOne("QuranDashboard.Domain.Quran.Words.QuranWord", null)
                        .WithMany()
                        .HasForeignKey("QuranWordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.Words.Display.UniqueSimpleWord", b =>
                {
                    b.HasOne("QuranDashboard.Domain.Quran.Words.QuranWord", null)
                        .WithMany()
                        .HasForeignKey("FirstQuranWordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.Words.Display.UniqueTashkeelWord", b =>
                {
                    b.HasOne("QuranDashboard.Domain.Quran.Words.QuranWord", null)
                        .WithMany()
                        .HasForeignKey("FirstQuranWordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.Words.Morphology.QuranLemma", b =>
                {
                    b.HasOne("QuranDashboard.Domain.Quran.Words.Morphology.QuranRoot", "Root")
                        .WithMany()
                        .HasForeignKey("RootId");

                    b.Navigation("Root");
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.Words.Morphology.WordMorphology", b =>
                {
                    b.HasOne("QuranDashboard.Domain.Quran.Words.Morphology.PosTag", null)
                        .WithMany()
                        .HasForeignKey("HeadPos")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuranDashboard.Domain.Quran.Words.Morphology.QuranLemma", "Lemma")
                        .WithMany()
                        .HasForeignKey("LemmaId");

                    b.HasOne("QuranDashboard.Domain.Quran.Words.QuranWord", "QuranWord")
                        .WithMany()
                        .HasForeignKey("QuranWordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuranDashboard.Domain.Quran.Words.Morphology.QuranRoot", "Root")
                        .WithMany()
                        .HasForeignKey("RootId");

                    b.HasOne("QuranDashboard.Domain.Quran.Words.Morphology.QuranStem", "Stem")
                        .WithMany()
                        .HasForeignKey("StemId");

                    b.Navigation("Lemma");

                    b.Navigation("QuranWord");

                    b.Navigation("Root");

                    b.Navigation("Stem");
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.Words.Morphology.WordMorphologySegment", b =>
                {
                    b.HasOne("QuranDashboard.Domain.Quran.Words.Morphology.Irab.QuranI3rabRule", "I3rabRule")
                        .WithMany()
                        .HasForeignKey("I3rabRuleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QuranDashboard.Domain.Quran.Words.Morphology.PosTag", null)
                        .WithMany()
                        .HasForeignKey("Pos")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuranDashboard.Domain.Quran.Words.QuranWord", "QuranWord")
                        .WithMany()
                        .HasForeignKey("QuranWordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("I3rabRule");

                    b.Navigation("QuranWord");
                });

            modelBuilder.Entity("QuranDashboard.Domain.Quran.Words.QuranWord", b =>
                {
                    b.HasOne("QuranDashboard.Domain.Quran.Ayahs.Ayah", "Ayah")
                        .WithMany()
                        .HasForeignKey("AyahId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuranDashboard.Domain.Quran.MushafPages.MushafPage", "Page")
                        .WithMany()
                        .HasForeignKey("PageNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ayah");

                    b.Navigation("Page");
                });
#pragma warning restore 612, 618
        }
    }
}
