using Microsoft.Extensions.DependencyInjection;
using QuranDashboard.Application.Quran.DataPipelines.Foundation;
using QuranDashboard.Application.Quran.DataPipelines.Foundation.Validation;
using QuranDashboard.Application.Quran.DataPipelines.Mutashabihat;
using QuranDashboard.Application.Quran.DataPipelines.Tafsirs;
using QuranDashboard.Application.Quran.DataPipelines.Translations;
using QuranDashboard.Application.Quran.DataPipelines.Navigation;
using QuranDashboard.Application.Quran.DataPipelines.Words.SimpleI3rabGeneration;
using QuranDashboard.Application.Quran.DataPipelines.Words.MorphologyImporting;
using QuranDashboard.Application.Quran.DataPipelines.Words.DisplayRebuilding;
using QuranDashboard.Application.Quran.DataPipelines.FullI3rab;
using QuranDashboard.Application.Quran.MushafReader.Queries.GetMushafPage;
using QuranDashboard.Application.Quran.MushafReader.Queries.GetAyahStudy;
using QuranDashboard.Application.Quran.MushafReader.Queries.GetMushafSurahCatalog;
using QuranDashboard.Application.Quran.MushafReader.Queries.GetMushafStudySourceCatalog;
using QuranDashboard.Application.Quran.MushafReader.Queries.GetAyahMutashabihat;
using QuranDashboard.Application.Quran.MushafReader.Queries.GetSimilarAyahs;
using QuranDashboard.Application.Quran.MushafReader.Queries.GetWordAnalysis;
using QuranDashboard.Application.Quran.Words.Queries.GetUniqueWordAyahs;
using QuranDashboard.Application.Quran.Words.Queries.GetUniqueWordMissingSurahs;
using QuranDashboard.Application.Quran.Words.Queries.GetUniqueWordSummary;
using QuranDashboard.Application.Quran.Words.Queries.GetUniqueWordSurahs;
using QuranDashboard.Application.Quran.Words.Queries.GetUniqueWordsPage;
using QuranDashboard.Application.Quran.Words.Roots.Queries.GetRootAyahs;
using QuranDashboard.Application.Quran.Words.Roots.Queries.GetRootLemmas;
using QuranDashboard.Application.Quran.Words.Roots.Queries.GetRootMentionedSurahs;
using QuranDashboard.Application.Quran.Words.Roots.Queries.GetRootMissingSurahs;
using QuranDashboard.Application.Quran.Words.Roots.Queries.GetRootsPage;
using QuranDashboard.Application.Quran.Words.Roots.Queries.GetRootStems;
using QuranDashboard.Application.Quran.Words.Roots.Queries.GetRootSummary;
using QuranDashboard.Application.Quran.Words.Roots.Queries.GetRootWords;
using QuranDashboard.Application.Quran.Words.Lemmas.Queries.GetLemmaAyahs;
using QuranDashboard.Application.Quran.Words.Lemmas.Queries.GetLemmaMissingSurahs;
using QuranDashboard.Application.Quran.Words.Lemmas.Queries.GetLemmaMentionedSurahs;
using QuranDashboard.Application.Quran.Words.Lemmas.Queries.GetLemmaStems;
using QuranDashboard.Application.Quran.Words.Lemmas.Queries.GetLemmaWords;
using QuranDashboard.Application.Quran.Words.Lemmas.Queries.GetLemmaSummary;
using QuranDashboard.Application.Quran.Words.Lemmas.Queries.GetLemmasPage;
using QuranDashboard.Application.Quran.Words.Stems.Queries.GetStemAyahs;
using QuranDashboard.Application.Quran.Words.Stems.Queries.GetStemMissingSurahs;
using QuranDashboard.Application.Quran.Words.Stems.Queries.GetStemMentionedSurahs;
using QuranDashboard.Application.Quran.Words.Stems.Queries.GetStemLemmas;
using QuranDashboard.Application.Quran.Words.Stems.Queries.GetStemWords;
using QuranDashboard.Application.Quran.Words.Stems.Queries.GetStemSummary;
using QuranDashboard.Application.Quran.Words.Stems.Queries.GetStemsPage;
using QuranDashboard.Application.Quran.Words.WordTypes.Queries.GetWordTypeAyahs;
using QuranDashboard.Application.Quran.Words.WordTypes.Queries.GetWordTypeRows;
using QuranDashboard.Application.Quran.Words.WordTypes.Queries.GetWordTypeTable;
using QuranDashboard.Application.Quran.Words.WordTypes.Queries.GetWordTypeGroupedSummary;
using QuranDashboard.Application.Quran.Words.WordTypes.Queries.GetWordTypeGroupedWords;
using QuranDashboard.Application.Quran.Words.WordTypes.Queries.GetWordTypeSummary;
using QuranDashboard.Application.Quran.Words.WordTypes.Queries.GetWordTypeSurahs;
using QuranDashboard.Application.Quran.Words.WordTypes.Queries.GetWordTypeTree;

namespace QuranDashboard.Application;

public static class DependencyInjection
{
    public static IServiceCollection AddApplication(this IServiceCollection services)
    {
        services.AddSingleton<QuranFoundationAssembler>();
        services.AddSingleton<QuranImportValidator>();
        services.AddScoped<ImportQuranFoundationHandler>();
        services.AddScoped<RebuildDisplayWordsHandler>();
        services.AddScoped<ImportMorphologyHandler>();
        services.AddScoped<ImportMutashabihatHandler>();
        services.AddScoped<ImportTafsirsHandler>();
        services.AddScoped<ImportTranslationsHandler>();
        services.AddScoped<ImportNavigationMetadataHandler>();
        services.AddScoped<ImportFullI3rabHandler>();
        services.AddScoped<GenerateI3rabHandler>();
        services.AddScoped<GetMushafPageHandler>();
        services.AddScoped<GetAyahStudyHandler>();
        services.AddScoped<GetMushafSurahCatalogHandler>();
        services.AddScoped<GetMushafStudySourceCatalogHandler>();
        services.AddScoped<GetWordAnalysisHandler>();
        services.AddScoped<GetSimilarAyahsHandler>();
        services.AddScoped<GetAyahMutashabihatHandler>();
        services.AddScoped<GetUniqueWordsPageHandler>();
        services.AddScoped<GetUniqueWordSummaryHandler>();
        services.AddScoped<GetUniqueWordSurahsHandler>();
        services.AddScoped<GetUniqueWordMissingSurahsHandler>();
        services.AddScoped<GetUniqueWordAyahsHandler>();
        services.AddScoped<GetRootsPageHandler>();
        services.AddScoped<GetRootSummaryHandler>();
        services.AddScoped<GetRootAyahsHandler>();
        services.AddScoped<GetRootWordsHandler>();
        services.AddScoped<GetRootMentionedSurahsHandler>();
        services.AddScoped<GetRootMissingSurahsHandler>();
        services.AddScoped<GetRootLemmasHandler>();
        services.AddScoped<GetRootStemsHandler>();
        services.AddScoped<GetLemmasPageHandler>();
        services.AddScoped<GetLemmaSummaryHandler>();
        services.AddScoped<GetLemmaAyahsHandler>();
        services.AddScoped<GetLemmaWordsHandler>();
        services.AddScoped<GetLemmaMentionedSurahsHandler>();
        services.AddScoped<GetLemmaMissingSurahsHandler>();
        services.AddScoped<GetLemmaStemsHandler>();
        services.AddScoped<GetStemsPageHandler>();
        services.AddScoped<GetStemSummaryHandler>();
        services.AddScoped<GetStemAyahsHandler>();
        services.AddScoped<GetStemWordsHandler>();
        services.AddScoped<GetStemMentionedSurahsHandler>();
        services.AddScoped<GetStemMissingSurahsHandler>();
        services.AddScoped<GetStemLemmasHandler>();
        services.AddScoped<GetWordTypeTreeHandler>();
        services.AddScoped<GetWordTypeRowsHandler>();
        services.AddScoped<GetWordTypeTableHandler>();
        services.AddScoped<GetWordTypeSummaryHandler>();
        services.AddScoped<GetWordTypeGroupedSummaryHandler>();
        services.AddScoped<GetWordTypeGroupedWordsHandler>();
        services.AddScoped<GetWordTypeAyahsHandler>();
        services.AddScoped<GetWordTypeSurahsHandler>();

        return services;
    }
}
