using Microsoft.Extensions.DependencyInjection;
using QuranDashboard.Application.Abwab.Commands.Sections.CreateSection;
using QuranDashboard.Application.Abwab.Commands.Sections.RenameSection;
using QuranDashboard.Application.Abwab.Commands.Sections.DeleteSection;
using QuranDashboard.Application.Abwab.Commands.Sections.ReorderSection;
using QuranDashboard.Application.Abwab.Commands.Doors.CreateDoor;
using QuranDashboard.Application.Abwab.Commands.Doors.EditDoor;
using QuranDashboard.Application.Abwab.Commands.Doors.MoveDoor;
using QuranDashboard.Application.Abwab.Commands.Doors.ReorderDoor;
using QuranDashboard.Application.Abwab.Commands.Doors.BulkMoveDoors;
using QuranDashboard.Application.Abwab.Commands.Doors.BulkArchiveDoors;
using QuranDashboard.Application.Abwab.Commands.Doors.DeleteDoor;
using QuranDashboard.Application.Abwab.Commands.Doors.RestoreDoor;
using QuranDashboard.Application.Abwab.Queries.GetAbwabTree;
using QuranDashboard.Application.Abwab.Queries.GetDoorRelations;
using QuranDashboard.Application.Abwab.Commands.Templates.AddTemplateNode;
using QuranDashboard.Application.Abwab.Commands.Templates.ApplyTemplate;
using QuranDashboard.Application.Abwab.Commands.Templates.CreateTemplate;
using QuranDashboard.Application.Abwab.Commands.Templates.DeleteTemplate;
using QuranDashboard.Application.Abwab.Commands.Templates.DeleteTemplateNode;
using QuranDashboard.Application.Abwab.Commands.Templates.EditTemplateNode;
using QuranDashboard.Application.Abwab.Commands.Templates.ReorderTemplateNode;
using QuranDashboard.Application.Abwab.Queries.GetTemplate;
using QuranDashboard.Application.Abwab.Queries.GetTemplates;
using QuranDashboard.Application.Abwab.Commands.Relations.AddDoorRelations;
using QuranDashboard.Application.Abwab.Commands.Relations.DeleteDoorRelation;
using QuranDashboard.Application.Abwab.Commands.AddDoorInclusions;
using QuranDashboard.Application.Abwab.Commands.DeleteDoorInclusion;
using QuranDashboard.Application.Abwab.Queries.GetDoorInclusions;
using QuranDashboard.Application.Access.Commands.ProvisionCurrentUser;
using QuranDashboard.Application.Access.Commands.CreateDeviceSession;
using QuranDashboard.Application.Access.Commands.RevokeDeviceSession;
using QuranDashboard.Application.Access.Commands.AcceptAccessUser;
using QuranDashboard.Application.Access.Commands.DisableAccessUser;
using QuranDashboard.Application.Access.Commands.ReactivateAccessUser;
using QuranDashboard.Application.Access.Commands.ReplaceUserPermissions;
using QuranDashboard.Application.Access.Commands.PreviewLogtoSubjectRelink;
using QuranDashboard.Application.Access.Commands.ConfirmLogtoSubjectRelink;
using QuranDashboard.Application.Access.LegacyRoleConversion;
using QuranDashboard.Application.Access.OwnerReconciliation;
using QuranDashboard.Application.Access.Queries.ListAccessUsers;
using QuranDashboard.Application.Access.Queries.GetAccessUser;
using QuranDashboard.Application.Access.Queries.GetPermissionCatalogue;
using QuranDashboard.Application.Access.Queries.GetUserPermissions;
using QuranDashboard.Application.Access.Queries.ListAccessAuditEvents;
using QuranDashboard.Application.Access.Queries.GetOwnerReconciliationStatus;
using QuranDashboard.Application.Abstractions.Access;
using QuranDashboard.Application.Quran.DataPipelines.Foundation;
using QuranDashboard.Application.Quran.DataPipelines.Foundation.Validation;
using QuranDashboard.Application.Quran.DataPipelines.Mutashabihat;
using QuranDashboard.Application.Quran.DataPipelines.Tafsirs;
using QuranDashboard.Application.Quran.DataPipelines.Translations;
using QuranDashboard.Application.Quran.DataPipelines.Navigation;
using QuranDashboard.Application.Quran.DataPipelines.Words.SimpleI3rabGeneration;
using QuranDashboard.Application.Quran.DataPipelines.Words.MorphologyImporting;
using QuranDashboard.Application.Quran.DataPipelines.Words.DisplayRebuilding;
using QuranDashboard.Application.Quran.DataPipelines.FullI3rab;
using QuranDashboard.Application.Quran.MushafReader.Queries.GetMushafPage;
using QuranDashboard.Application.Quran.MushafReader.Queries.GetMushafDoorHighlights;
using QuranDashboard.Application.Quran.MushafReader.Queries.GetAyahStudy;
using QuranDashboard.Application.Quran.MushafReader.Queries.GetMushafSurahCatalog;
using QuranDashboard.Application.Quran.MushafReader.Queries.GetMushafStudySourceCatalog;
using QuranDashboard.Application.Quran.MushafReader.Queries.GetAyahMutashabihat;
using QuranDashboard.Application.Quran.MushafReader.Queries.GetSimilarAyahs;
using QuranDashboard.Application.Quran.MushafReader.Queries.GetWordAnalysis;
using QuranDashboard.Application.Quran.Words.Queries.GetUniqueWordAyahs;
using QuranDashboard.Application.Quran.Words.Queries.GetUniqueWordMissingSurahs;
using QuranDashboard.Application.Quran.Words.Queries.GetUniqueWordSummary;
using QuranDashboard.Application.Quran.Words.Queries.GetUniqueWordSurahs;
using QuranDashboard.Application.Quran.Words.Queries.GetUniqueWordsPage;
using QuranDashboard.Application.Quran.Words.Roots.Queries.GetRootAyahs;
using QuranDashboard.Application.Quran.Words.Roots.Queries.GetRootLemmas;
using QuranDashboard.Application.Quran.Words.Roots.Queries.GetRootMentionedSurahs;
using QuranDashboard.Application.Quran.Words.Roots.Queries.GetRootMissingSurahs;
using QuranDashboard.Application.Quran.Words.Roots.Queries.GetRootsPage;
using QuranDashboard.Application.Quran.Words.Roots.Queries.GetRootStems;
using QuranDashboard.Application.Quran.Words.Roots.Queries.GetRootSummary;
using QuranDashboard.Application.Quran.Words.Roots.Queries.GetRootWords;
using QuranDashboard.Application.Quran.Words.Lemmas.Queries.GetLemmaAyahs;
using QuranDashboard.Application.Quran.Words.Lemmas.Queries.GetLemmaMissingSurahs;
using QuranDashboard.Application.Quran.Words.Lemmas.Queries.GetLemmaMentionedSurahs;
using QuranDashboard.Application.Quran.Words.Lemmas.Queries.GetLemmaStems;
using QuranDashboard.Application.Quran.Words.Lemmas.Queries.GetLemmaWords;
using QuranDashboard.Application.Quran.Words.Lemmas.Queries.GetLemmaSummary;
using QuranDashboard.Application.Quran.Words.Lemmas.Queries.GetLemmasPage;
using QuranDashboard.Application.Quran.Words.Stems.Queries.GetStemAyahs;
using QuranDashboard.Application.Quran.Words.Stems.Queries.GetStemMissingSurahs;
using QuranDashboard.Application.Quran.Words.Stems.Queries.GetStemMentionedSurahs;
using QuranDashboard.Application.Quran.Words.Stems.Queries.GetStemLemmas;
using QuranDashboard.Application.Quran.Words.Stems.Queries.GetStemWords;
using QuranDashboard.Application.Quran.Words.Stems.Queries.GetStemSummary;
using QuranDashboard.Application.Quran.Words.Stems.Queries.GetStemsPage;
using QuranDashboard.Application.Quran.Words.WordTypes.Queries.GetWordTypeAyahs;
using QuranDashboard.Application.Quran.Words.WordTypes.Queries.GetWordTypeRows;
using QuranDashboard.Application.Quran.Words.WordTypes.Queries.GetWordTypeTable;
using QuranDashboard.Application.Quran.Words.WordTypes.Queries.GetWordTypeScopeCounts;
using QuranDashboard.Application.Quran.Words.WordTypes.Queries.GetWordTypeGroupedSummary;
using QuranDashboard.Application.Quran.Words.WordTypes.Queries.GetWordTypeGroupedWords;
using QuranDashboard.Application.Quran.Words.WordTypes.Queries.GetWordTypeGroupedAyahs;
using QuranDashboard.Application.Quran.Words.WordTypes.Queries.GetWordTypeGroupedSurahs;
using QuranDashboard.Application.Quran.Words.WordTypes.Queries.GetWordTypeSummary;
using QuranDashboard.Application.Quran.Words.WordTypes.Queries.GetWordTypeSurahs;
using QuranDashboard.Application.Quran.Words.WordTypes.Queries.GetWordTypeTree;
using QuranDashboard.Application.Linking.Queries.ResolveLinkingSourcePage;
using QuranDashboard.Application.Linking.Queries.GetLinkingWorkspace;
using QuranDashboard.Application.Linking.DoorLinks.Queries.GetDoorLinkAyahs;
using QuranDashboard.Application.Linking.DoorLinks.Queries.GetDoorLinkRecords;
using QuranDashboard.Application.Linking.DoorLinks.Queries.GetDoorLinkSnapshot;
using QuranDashboard.Application.Linking.DoorLinks.Commands.DeleteDoorLinks;
using QuranDashboard.Application.Linking.DoorLinks.Commands.ReplaceDoorLinkWords;
using QuranDashboard.Application.Linking.Commands.AddLinkingWorkspaceSource;
using QuranDashboard.Application.Linking.Commands.ClearLinkingWorkspaceSources;
using QuranDashboard.Application.Linking.Commands.RemoveLinkingWorkspaceSource;
using QuranDashboard.Application.Linking.Commands.ReorderLinkingWorkspaceSources;
using QuranDashboard.Application.Linking.Commands.UpdateLinkingWorkspaceSourceTypes;
using QuranDashboard.Application.Linking.Commands.ApplyLinkingWorkspaceSourceDelta;
using QuranDashboard.Application.Linking.PreparedPreflights;
using QuranDashboard.Application.Abstractions.Linking.PreparedPreflights;
using QuranDashboard.Application.Linking.ConfirmationJobs;
using QuranDashboard.Application.Abstractions.Linking.ConfirmationJobs;

namespace QuranDashboard.Application;

public static class DependencyInjection
{
    public static IServiceCollection AddApplication(this IServiceCollection services)
    {
        services.AddSingleton<QuranFoundationAssembler>();
        services.AddSingleton<QuranImportValidator>();
        services.AddScoped<ImportQuranFoundationHandler>();
        services.AddScoped<RebuildDisplayWordsHandler>();
        services.AddScoped<ImportMorphologyHandler>();
        services.AddScoped<ImportMutashabihatHandler>();
        services.AddScoped<ImportTafsirsHandler>();
        services.AddScoped<ImportTranslationsHandler>();
        services.AddScoped<ImportNavigationMetadataHandler>();
        services.AddScoped<ImportFullI3rabHandler>();
        services.AddScoped<GenerateI3rabHandler>();
        services.AddScoped<GetMushafPageHandler>();
        services.AddScoped<GetMushafDoorHighlightsHandler>();
        services.AddScoped<GetAyahStudyHandler>();
        services.AddScoped<GetMushafSurahCatalogHandler>();
        services.AddScoped<GetMushafStudySourceCatalogHandler>();
        services.AddScoped<GetWordAnalysisHandler>();
        services.AddScoped<GetSimilarAyahsHandler>();
        services.AddScoped<GetAyahMutashabihatHandler>();
        services.AddScoped<GetUniqueWordsPageHandler>();
        services.AddScoped<GetUniqueWordSummaryHandler>();
        services.AddScoped<GetUniqueWordSurahsHandler>();
        services.AddScoped<GetUniqueWordMissingSurahsHandler>();
        services.AddScoped<GetUniqueWordAyahsHandler>();
        services.AddScoped<GetRootsPageHandler>();
        services.AddScoped<GetRootSummaryHandler>();
        services.AddScoped<GetRootAyahsHandler>();
        services.AddScoped<GetRootWordsHandler>();
        services.AddScoped<GetRootMentionedSurahsHandler>();
        services.AddScoped<GetRootMissingSurahsHandler>();
        services.AddScoped<GetRootLemmasHandler>();
        services.AddScoped<GetRootStemsHandler>();
        services.AddScoped<GetLemmasPageHandler>();
        services.AddScoped<GetLemmaSummaryHandler>();
        services.AddScoped<GetLemmaAyahsHandler>();
        services.AddScoped<GetLemmaWordsHandler>();
        services.AddScoped<GetLemmaMentionedSurahsHandler>();
        services.AddScoped<GetLemmaMissingSurahsHandler>();
        services.AddScoped<GetLemmaStemsHandler>();
        services.AddScoped<GetStemsPageHandler>();
        services.AddScoped<GetStemSummaryHandler>();
        services.AddScoped<GetStemAyahsHandler>();
        services.AddScoped<GetStemWordsHandler>();
        services.AddScoped<GetStemMentionedSurahsHandler>();
        services.AddScoped<GetStemMissingSurahsHandler>();
        services.AddScoped<GetStemLemmasHandler>();
        services.AddScoped<GetWordTypeTreeHandler>();
        services.AddScoped<GetWordTypeRowsHandler>();
        services.AddScoped<GetWordTypeTableHandler>();
        services.AddScoped<GetWordTypeScopeCountsHandler>();
        services.AddScoped<GetWordTypeSummaryHandler>();
        services.AddScoped<GetWordTypeGroupedSummaryHandler>();
        services.AddScoped<GetWordTypeGroupedWordsHandler>();
        services.AddScoped<GetWordTypeGroupedAyahsHandler>();
        services.AddScoped<GetWordTypeGroupedSurahsHandler>();
        services.AddScoped<GetWordTypeAyahsHandler>();
        services.AddScoped<GetWordTypeSurahsHandler>();

        services.AddScoped<ProvisionCurrentUserHandler>();
        services.AddScoped<CreateDeviceSessionHandler>();
        services.AddScoped<RevokeDeviceSessionHandler>();
        services.AddScoped<ListAccessUsersHandler>();
        services.AddScoped<GetAccessUserHandler>();
        services.AddScoped<AcceptAccessUserHandler>();
        services.AddScoped<DisableAccessUserHandler>();
        services.AddScoped<ReactivateAccessUserHandler>();
        services.AddScoped<GetPermissionCatalogueHandler>();
        services.AddScoped<GetUserPermissionsHandler>();
        services.AddScoped<ReplaceUserPermissionsHandler>();
        services.AddScoped<ListAccessAuditEventsHandler>();
        services.AddScoped<PreviewLogtoSubjectRelinkHandler>();
        services.AddScoped<ConfirmLogtoSubjectRelinkHandler>();
        services.AddScoped<GetOwnerReconciliationStatusHandler>();
        services.AddOwnerReconciliation();

        services.AddScoped<CreateSectionHandler>();
        services.AddScoped<RenameSectionHandler>();
        services.AddScoped<DeleteSectionHandler>();
        services.AddScoped<ReorderSectionHandler>();

        services.AddScoped<CreateDoorHandler>();
        services.AddScoped<EditDoorHandler>();
        services.AddScoped<MoveDoorHandler>();
        services.AddScoped<ReorderDoorHandler>();
        services.AddScoped<BulkMoveDoorsHandler>();
        services.AddScoped<BulkArchiveDoorsHandler>();
        services.AddScoped<DeleteDoorHandler>();
        services.AddScoped<RestoreDoorHandler>();
        services.AddScoped<GetAbwabTreeHandler>();
        services.AddScoped<GetDoorRelationsHandler>();
        services.AddScoped<AddDoorRelationsHandler>();
        services.AddScoped<DeleteDoorRelationHandler>();
        services.AddScoped<GetDoorInclusionsHandler>();
        services.AddScoped<AddDoorInclusionsHandler>();
        services.AddScoped<DeleteDoorInclusionHandler>();

        services.AddScoped<GetTemplatesHandler>();
        services.AddScoped<GetTemplateHandler>();
        services.AddScoped<CreateTemplateHandler>();
        services.AddScoped<DeleteTemplateHandler>();
        services.AddScoped<AddTemplateNodeHandler>();
        services.AddScoped<EditTemplateNodeHandler>();
        services.AddScoped<ReorderTemplateNodeHandler>();
        services.AddScoped<DeleteTemplateNodeHandler>();
        services.AddScoped<ApplyTemplateHandler>();

        services.AddScoped<ResolveLinkingSourcePageHandler>();
        services.AddScoped<GetLinkingWorkspaceHandler>();
        services.AddScoped<GetDoorLinkRecordsHandler>();
        services.AddScoped<GetDoorLinkSnapshotHandler>();
        services.AddScoped<GetDoorLinkAyahsHandler>();
        services.AddScoped<ReplaceDoorLinkWordsHandler>();
        services.AddScoped<DeleteDoorLinksHandler>();
        services.AddScoped<AddLinkingWorkspaceSourceHandler>();
        services.AddScoped<RemoveLinkingWorkspaceSourceHandler>();
        services.AddScoped<ReorderLinkingWorkspaceSourcesHandler>();
        services.AddScoped<ApplyLinkingWorkspaceSourceDeltaHandler>();
        services.AddScoped<UpdateLinkingWorkspaceSourceTypesHandler>();
        services.AddScoped<ClearLinkingWorkspaceSourcesHandler>();
        services.AddScoped<CreateLinkingPreparedPreflightHandler>();
        services.AddScoped<GetLinkingPreparedPreflightHandler>();
        services.AddScoped<CancelLinkingPreparedPreflightHandler>();
        services.AddScoped<GetLinkingPreparedDetailPageHandler>();
        services.AddScoped<ProcessLinkingPreparedPreflightHandler>();
        services.AddScoped<ILinkingPreparedPreflightProcessor, ProcessLinkingPreparedPreflightHandler>();
        services.AddSingleton<LinkingPreparedPreflightLeaseService>();
        services.AddScoped<LinkingPreparedPreflightInputBuilder>();
        services.AddScoped<CreateLinkingConfirmationJobHandler>();
        services.AddScoped<GetLinkingConfirmationJobHandler>();
        services.AddScoped<CancelLinkingConfirmationJobHandler>();
        services.AddScoped<GetLinkingConfirmationOutcomeHandler>();
        services.AddScoped<ProcessLinkingConfirmationJobHandler>();
        services.AddScoped<ILinkingConfirmationJobProcessor, ProcessLinkingConfirmationJobHandler>();
        services.AddSingleton<LinkingConfirmationJobLeaseService>();

        return services;
    }

    public static IServiceCollection AddOwnerReconciliation(this IServiceCollection services)
    {
        services.AddScoped<IOwnerReconciliationService, OwnerReconciliationService>();
        services.AddScoped<ILegacyRoleConversionService, LegacyRoleConversionService>();
        return services;
    }
}
